### ISSUE TITLE
Add distribution and histogram metric support

### ISSUE THREAD

**Issue by nlehrer** [GoogleCloudPlatform/opentelemetry-operations-js#101]
Only non-distribution (bool, int64, double, etc.) values are supported by the exporter at the moment. See [this](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/a1f6264bec877bc00c66348d249ac076d8cf0207/packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts#L177) line of code for the relevant TODO and where support should be added (perhaps among other places).

**Comment by nlehrer** [comment]
Check if a distribution without buckets is rejected by the API.

**Comment by coreyvan** [comment]
Are histograms and distribution metric kinds supported now? I noticed that a fix got merged in as part of #125 but there's still this method that sets the `MetricKind` to `UNSPECIFIED` (which causes GCP to reject the metric descriptor) here: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/60f90dccefe2f903b67c28a61cd78300fae4737a/packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts#L72-L85

**Comment by nlehrer** [comment]
It does seem from that code that it is still not supported but that it could be easy to complete the support. A new owner needs to be found for this issue since @TigerHe7 is no longer working on this project (neither am I).
