### ISSUE TITLE
cloud monitoring exporter is not compatible with the latest release of @opentelemetry/metrics

### ISSUE THREAD

**Issue by reggiemcdonald** [GoogleCloudPlatform/opentelemetry-operations-js#102]
### What version of OpenTelemetry are you using?
@opentelemetry/metrics@0.9.0

### What version of Node are you using?
13

### What did you do?
Starting with a new directory, copied and ran the sample code in the README [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/master/packages/opentelemetry-cloud-monitoring-exporter/README.md).

I installed two dependencies: 
- `@opentelemetry/metrics@0.9.0`
- `@google-cloud/opentelemetry-cloud-monitoring-exporter`

and added the appropriate ADC for google cloud.

Finally, I made a logger set to debug, and passed it as an option to the `MetricExporter`

### What did you expect to see?
The metrics should have been sent to cloud monitoring and visible within the console.

### What did you see instead?
An error message was thrown instead, and the metrics were not uploaded: 
```
Google Cloud Monitoring export
TypeError: Cannot read property 'map' of undefined
    at transformLabelDescriptor (/Users/reginaldmcdonald/Documents/github/metrics-example/node_modules/@google-cloud/opentelemetry-cloud-monitoring-exporter/build/src/transform.js:46:43)
    at Object.transformMetricDescriptor (/Users/reginaldmcdonald/Documents/github/metrics-example/node_modules/@google-cloud/opentelemetry-cloud-monitoring-exporter/build/src/transform.js:32:17)
    at MetricExporter._createMetricDescriptor (/Users/reginaldmcdonald/Documents/github/metrics-example/node_modules/@google-cloud/opentelemetry-cloud-monitoring-exporter/build/src/monitoring.js:118:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async MetricExporter._registerMetricDescriptor (/Users/reginaldmcdonald/Documents/github/metrics-example/node_modules/@google-cloud/opentelemetry-cloud-monitoring-exporter/build/src/monitoring.js:99:30)
    at async MetricExporter.export (/Users/reginaldmcdonald/Documents/github/metrics-example/node_modules/@google-cloud/opentelemetry-cloud-monitoring-exporter/build/src/monitoring.js:72:34)
done
```

In typescript, the above example will produce a type conflict, and will not compile. 

If I swap out `@opentelemetry/metrics@0.9.0` with an older 0.6.1 release, then the code runs fine and the metric is visible from the cloud console. 

### Additional context
This is likely to do with a change to the opentelemetry spec where labelKeys have been removed [here](https://github.com/open-telemetry/opentelemetry-js/commit/c24d9923054fff431feb215c47c6c5647973dfe6#diff-0cdf7b503ad3cf97f7b836b0cf885210) and [here](https://github.com/open-telemetry/opentelemetry-js/commit/c24d9923054fff431feb215c47c6c5647973dfe6#diff-e3728f5692d938914d82d335cd641267)

We can see that in the metric descriptor transformer, it's assumed that this key still exists: 
https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/3ecb2e240e66f5b8cfbfa65d6a62ada3329feda3/packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts#L38-L52

which results in the above type error when the following code is executed: 
https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/3ecb2e240e66f5b8cfbfa65d6a62ada3329feda3/packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts#L65-L77

**Comment by reggiemcdonald** [comment]
I'm pretty interested in giving this a shot if thats okay?

**Comment by reggiemcdonald** [comment]
There were quite a few new `MetricKind`s added to [opentelemetry/metrics](https://github.com/open-telemetry/opentelemetry-js/commit/a655d2b1ca7df3ddf4457fe406a990f621c46a9f#diff-0cdf7b503ad3cf97f7b836b0cf885210) since the last release of the exporter.

I was wondering if I could get some input into whether I'm mapping `MetricKind` to the appropriate Cloud Monitoring type? 

```
function transformMetricKind(kind: OTMetricKind): MetricKind {
  switch (kind) {
    case OTMetricKind.COUNTER:
    case OTMetricKind.SUM_OBSERVER:
      return MetricKind.CUMULATIVE;
    case OTMetricKind.UP_DOWN_COUNTER:
    // OTMetricKind.OBSERVER will be removed in opentelemetry-js #1146
    case OTMetricKind.OBSERVER:
    case OTMetricKind.VALUE_OBSERVER:
    case OTMetricKind.UP_DOWN_SUM_OBSERVER:
      return MetricKind.GAUGE;
    default:
      // TODO: Add support for OTMetricKind.ValueRecorder
      // OTMetricKind.Measure was renamed to ValueRecorder in #1117
      return MetricKind.UNSPECIFIED;
  }
}
```
[source](https://github.com/reggiemcdonald/opentelemetry-operations-js/blob/de3aecb879b27a2bc2be9e527f61261f2b999219/packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts#L68-L84)

**Comment by aabmass** [comment]
Here's what is done in the python one right now. It doesn't look exhaustive, but any of the instruments that use a sum aggregator output a gauge:
https://github.com/open-telemetry/opentelemetry-python/blob/3c366b2a65b41be9c90c34d13cc9a26cb76310ab/ext/opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py#L128-L135
