### ISSUE TITLE
use gRPC to send metrics to cloud monitoring

### ISSUE THREAD

**Issue by reggiemcdonald** [GoogleCloudPlatform/opentelemetry-operations-js#103]
The current implementation of the MetricExporter sends metric data using REST: 
https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/3ecb2e240e66f5b8cfbfa65d6a62ada3329feda3/packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts#L215-L224

This is inconsistent with other implementations of the GCP exporters such as the go implementation which uses gRPC.

*Describe the solution you'd like*
Refactor the MetricExporter to send the metric data using gRPC.

**Comment by aabmass** [comment]
I think this requirement came from a previous version of our spec that said we should use gRPC. I don't think there is a strong reason to do this right now. We can reopen if REST proves too slow but closing for now.
