### ISSUE TITLE
Trace through Cloud Pub/Sub

### ISSUE THREAD

**Issue by davedc** [GoogleCloudPlatform/opentelemetry-operations-js#104]
*Is your feature request related to a problem? Please describe.*
Trace context is not passed in on publish on a topic. This leads to detached spans created on subscribers.

*Describe the solution you'd like*
A `@opentelemetry/plugin-gcp-pubsub` and a `GCPPubSubPropagator` class to automatically inject and extract Context.

*Describe alternatives you've considered*
Manually injecting the trace context via Message attributes but no way to extract on the other side.

*Additional context*
Am expecting something similar to this https://github.com/googleapis/cloud-trace-nodejs/issues/1076#issuecomment-516233799 without manually having to create spans.

Please kindly point me to the right place if this isn't the correct repo to submit this feature request. Thanks!

**Comment by punya** [comment]
Is this solved by https://github.com/googleapis/nodejs-pubsub/pull/1078?

**Comment by aabmass** [comment]
Yes, pubsub node is instrumented directly now 🙂 I'm going to close this

**Comment by weyert** [comment]
Yes, this ticket can be closed, but love to get some feedback from Google Trace Opentelemetry team about the attributes I am sending and if it matches what the spec had it mind. I think in future releases of google-pubsub improvements can be made :)

**Comment by aabmass** [comment]
I'll take a look at the pubsub PR
