### ISSUE TITLE
node.js sample should not require to set projectID when run on Google Cloud

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/opentelemetry-operations-js#106]
https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/3ecb2e240e66f5b8cfbfa65d6a62ada3329feda3/samples/trace/index.js#L26-L43

The sample spends a lot of line trying to get project ID

According to [this issue](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/98), this is not needed when deploying on Google Cloud (to GCE, GKE, Cloud Run, Functions, GAE....)

CC @inlined

**Comment by jonahrosenblum** [comment]
Hello, since this is related to the other issue I was working on do you mind if I take this one as well?

**Comment by steren** [comment]
If the question is for me, please do :) I was not planning on taking it.

**Comment by aabmass** [comment]
Looks like this was fixed 🙂
