### ISSUE TITLE
OAuth2 request is not filtered

### ISSUE THREAD

**Issue by kintel** [GoogleCloudPlatform/opentelemetry-operations-js#11]
I've written a minimal node.js client using `NodeTracerProvider`.
A simple test run uncovered that the OAuth2 request is not filtered, and shows up as `POST /oauth2/v4/token` in the Cloud Trace backend.

I can dig around a bit myself, but opening this in case someone already knows why.

Note: This works as expected using the OpenCensus agent with pretty much the same client implementation.

**Comment by mayurkale22** [comment]
Thanks for reporting this! If you are feeling motivated, maybe you can attempt to write solution and open a PR.

**Comment by kintel** [comment]
I'll keep it on my list. Writing a solution is likely the easy part. Getting integration tests set up for this may prove to be significantly more effort : /

**Comment by aabmass** [comment]
I am no longer seeing this issue. Instrumentation is now suppressed in the [BatchSpanProcessor](https://github.com/open-telemetry/opentelemetry-js/blob/bf99144ad4e4fa38120e896d70e9e5bcfaf27054/packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts#L112) and [SimpleSpanProcessor](https://github.com/open-telemetry/opentelemetry-js/blob/bf99144ad4e4fa38120e896d70e9e5bcfaf27054/packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts#L50) from https://github.com/open-telemetry/opentelemetry-js/pull/1344
