### ISSUE TITLE
Consider using NPM peer dependencies

### ISSUE THREAD

**Issue by kintel** [GoogleCloudPlatform/opentelemetry-operations-js#112]
I've run into a few situations where the OpenTelemetry libraries required by the exporter conflicts with the one required by my app. Having two instances of OpenTelemetry like that is probably not what we want.
NPM  has a solution for this called [Peer Dependencies](https://docs.npmjs.com/files/package.json#peerdependencies).

Should we make use of peer dependencies for this exporter?

**Comment by aabmass** [comment]
Sounds like a good idea to me
