### ISSUE TITLE
Massive amount of spans ingested

### ISSUE THREAD

**Issue by ljcremer** [GoogleCloudPlatform/opentelemetry-operations-js#117]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
"@opentelemetry/api": "^0.9.0",
"@opentelemetry/node": "^0.9.0",
"@google-cloud/opentelemetry-cloud-trace-exporter": "^0.3.0",

### What version of Node are you using?
10

### What did you do?
If possible, provide a recipe for reproducing the error.
We are using Google Cloud Trace and and Stackdriver logging in our project. It has been working well but during the last two weeks we are seeing a massive amount of spans ingested with very little traffic on the project. Last month we had around 95K spans ingested and this month so far it increased to around 50M and we are only half way into the month

### What did you expect to see?
Normal amount of spans ingested as we have very low traffic in a development environment

### What did you see instead?
Increase from 90K spans ingested last month to around 50M spans ingested in the last two weeks

### Additional context
We are also experiencing network delays on our Google project when the GAE application connects to MySQL and Google Cloud storage. 

The following traces are also showing up that never did:
POST /v2/projects/trooptravel-v1/traces:batchWrite

With the following labels where the 429 status code is a bit concerning
Label | Value
net.peer.port | 443
net.peer.name | cloudtrace.googleapis.com
http.status_text | TOO MANY REQUESTS
g.co/agent | opentelemetry-js [0.7.0]; google-cloud-trace-exporter [0.2.0]
net.peer.ip | 74.125.126.95
telemetry.sdk.name | opentelemetry
http.url | https://cloudtrace.googleapis.com/v2/projects/trooptravel-v1/traces:batchWrite
telemetry.sdk.version | 0.9.0
component | https
project_id | trooptravel-v1
net.transport | IP.TCP
http.method | POST
telemetry.sdk.language | nodejs
http.target | /v2/projects/trooptravel-v1/traces:batchWrite
http.flavor | 1.1
http.status_code | 429
http.host | cloudtrace.googleapis.com:443

**Comment by aabmass** [comment]
@ljcremer does this uptick line up with when you upgraded to `@opentelemetry/node": "^0.9.0`? There hasn't been a release of this package in ~3 months.

**Comment by ljcremer** [comment]
@aabmass I am not sure what exactly triggered it but it started around the 2nd of July. We also did a big release then and a lot of things changed. 

We have done a lot more investigation and we think it is to do with the fact that 
the https plugin is picking up the post for the trace batch write and then it potentially creates an infinite loop. It seems to be related to the issue discussed here: [Infinite loop](https://github.com/open-telemetry/opentelemetry-js/issues/332)
If this is the case the best place to fix it probably is in the http / https plugins

We are still investigating and will do an update here when we find the exact issue.

**Comment by ljcremer** [comment]
It seems like the infinite loop could have been the issue as discussed in the previous comment. 

The way we fixed this is to add the following into the config of the http and https plugins when creating the trace provider. If you do not do this the tracer creates a new span each time the exporter logs the previous span with the batchWrite post. 

        const tracerProvider = new NodeTracerProvider({
            plugins: {
                http: {
                    enabled: this.plugins.http === true ? true : false,
                    path: "@opentelemetry/plugin-http",
                    ignoreOutgoingUrls: [/traces:batchWrite/]
                },
                https: {
                    enabled: this.plugins.https === true ? true : false,
                    path: "@opentelemetry/plugin-https",
                    ignoreOutgoingUrls: [/traces:batchWrite/]
                },
                express: {
                    enabled: this.plugins.express === true ? true : false,
                    path: "@opentelemetry/plugin-express"
                },
                mysql: {
                    enabled: this.plugins.mysql === true ? true : false,
                    path: "@opentelemetry/plugin-mysql"
                },
            }
        });

**Comment by aabmass** [comment]
@ljcremer thanks for looking into it. Hopefully it can be fixed on the opentelemetry-js side

**Comment by marcoreni** [comment]
opentelemetry-js released a change to be able to filter gRPC requests: https://github.com/open-telemetry/opentelemetry-js/pull/1353 . Requests having `x-opentelemetry-outgoing-request` are automatically filtered, so I presume this can be considered solved?

**Comment by aabmass** [comment]
I'm going to close this for now 👍
