### ISSUE TITLE
Cloud propagator package is missing one file and breaks compilation

### ISSUE THREAD

**Issue by jsiddiqui** [GoogleCloudPlatform/opentelemetry-operations-js#141]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?

0.10.1

### What version of Node are you using?

13.12.0

### What did you do?
If possible, provide a recipe for reproducing the error.

used cloud trace propagator as per instructions at https://www.npmjs.com/package/@google-cloud/opentelemetry-cloud-trace-propagator

### What did you expect to see?

The trace propagator working without errors.

### What did you see instead?

```
Error: Cannot find module './CloudPropagator'
Require stack:
- .../node_modules/@google-cloud/opentelemetry-cloud-trace-propagator/build/src/index.js:26:14
```

### Additional context

The CloudPropagator.ts file added in #116 does not seem to be included in the published NPM module.

**Comment by sk-** [comment]
The type definitions are also missing.

Take a look at the contents of the package: https://unpkg.com/browse/@google-cloud/opentelemetry-cloud-trace-propagator@0.4.0/

**Comment by aabmass** [comment]
@shivkanya9146 could you take a look?

**Comment by mayurkale22** [comment]
Looks like there is a typos in `package.json` files property, see: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/master/packages/opentelemetry-cloud-trace-propagator/package.json#L29-L30

Ideally, it should be like:
```
"build/src/**/*.js",
"build/src/**/*.d.ts",
```

**Comment by pr4v33n** [comment]
I still see the same error, I'm using `0.4.0` of `@google-cloud/opentelemetry-cloud-trace-propagator`

**Comment by mayurkale22** [comment]
The new package is not yet released, we planned to cut new release early tomorrow. Sorry for the inconvenience.
