### ISSUE TITLE
Missing Cloud Monitoring user agent

### ISSUE THREAD

**Issue by aabmass** [GoogleCloudPlatform/opentelemetry-operations-js#152]
This is implemented in the Go exporter already, see [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/5fb47d1fa010a14731ca4fcee9bd5e57b25bd5b2/exporter/metric/option.go#L29) and [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/7454a7ef9c1361afe6b8b2d33e4b85a67c5db897/exporter/metric/metric.go#L124).

**Comment by psx95** [comment]
Currently being worked on

**Comment by aabmass** [comment]
Fixed in https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/451
