### ISSUE TITLE
0.4.2 requires deprecated @opentelemetry/base@0.7.0 to be installed 

### ISSUE THREAD

**Issue by jsiddiqui** [GoogleCloudPlatform/opentelemetry-operations-js#156]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?

0.10.2

### What version of Node are you using?

v12

### What did you do?
If possible, provide a recipe for reproducing the error.

Install 0.4.2 version with opentelemetry 0.10.2

### What did you expect to see?

Compile without issues

### What did you see instead?

Got module not found error for "@opentelemetry/base" in cloud-trace-exporter code

### Additional context

Deprecated peer dependency @opentelemetry/base is required (https://www.npmjs.com/package/@opentelemetry/base). It has been merged in @opentelemetry/core now. The deprecated package @opentelemetry/base@0.7.0 can be added in package.json but I am not sure if mixing @opentelemetry/base@0.7.0 and @opentelemetry/core@0.10.2 will be stable as both will contain different versions of same code. 

For now, I have kept exporter at 0.4.1 (thus having a whole separate copy of @opentelemetry at 0.7.0) and propagator at 0.4.2 (as that only works with peer dependencies due to the way opentelemetry context works)

The solution, I think, is to update the dependencies of cloud-trace-exporter to 0.8.0 or later when @opentelemetry/base and @opentelemetry/core have been merged and fix the require statements therein.

**Comment by aabmass** [comment]
@jsiddiqui thanks for the report. I will definitely upgrade to `>=0.8.0` and remove `@opentelemetry/base` peer dependency! I think the version specifier also can't be caret because of [this edge case in semver](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) when major version is 0, so I will use `>=0.8.0 <1.0.0-0`.

**Comment by jsiddiqui** [comment]
Thanks Aaron. Probably >=0.8.0 and <=0.10.x is better as 0.11 could bring breaking changes by semver rules (core getting renamed, etc.)

Someone could still use 0.11 (when it comes) and npm will only generate a warning. The error in this particular case was only because two package got merged.

**Comment by aabmass** [comment]
Ah I see what you mean about the version.

> The error in this particular case was only because two package got merged.

What's strange is I tested this and it does fix the issue, even though there is still an import for `@opentelemetry/base`: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/aa8a6441c36931ca40b438a61c8060da2ad7a426/packages/opentelemetry-cloud-trace-exporter/src/trace.ts#L15

**Comment by jsiddiqui** [comment]
@aabmass Can you make a new release

**Comment by aabmass** [comment]
Published
