### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by nlehrer** [GoogleCloudPlatform/opentelemetry-operations-js#157]
We should add integration tests covering the behavior of the exporter when writing to the Cloud Monitoring and Cloud Trace backends.

Please see [this design](https://docs.google.com/document/d/1AAY6iGckJYRV8UCX1LXWFF52eRzIqXL2-0t3jtOHbFk/edit) for how to achieve integration tests for Cloud Trace written by Reg Mcdonald (reggiemcdonald on GitHub) and Tiger He (TigerHe7 on GitHub) when they were Google interns. Now that they are not interns anymore, someone else will probably need to implement the design.

**Comment by aabmass** [comment]
Fixed by #278
