### ISSUE TITLE
Create metrics sample

### ISSUE THREAD

**Issue by aabmass** [GoogleCloudPlatform/opentelemetry-operations-js#158]
*NB:* Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

*Is your feature request related to a problem? Please describe.*
Create a metrics sample

*Describe the solution you'd like*
A sample for metrics, like there is for trace in `samples/trace`.

*Describe alternatives you've considered*
n/a

*Additional context*
no

**Comment by psx95** [comment]
@aabmass doesn't have the capacity to work on it right now, but would be happy to review a PR for this.
