### ISSUE TITLE
[cloud trace propagator] TRACE_TRUE in header is optional

### ISSUE THREAD

**Issue by nareddyt** [GoogleCloudPlatform/opentelemetry-operations-js#161]
@google-cloud/opentelemetry-cloud-trace-propagator

The propagator currently assumes the `x-cloud-trace-header` matches the following format:

```
"X-Cloud-Trace-Context: TRACE_ID/SPAN_ID;o=TRACE_TRUE"
```

However, it seems like the last part `;o=TRACE_TRUE` is optional. 

https://github.com/googleapis/google-cloud-dotnet/issues/3055 is the same discussion and fix for `.NET` propagator.

You can also verify this behavior by visiting my custom Cloud Run service [here](https://espv2-proxy-lrnm3ejpeq-uc.a.run.app/hello). The backend is logging all headers it receives and echoing them back as a JSON body. Key details:
- Notice the `x-cloud-trace-context` header is missing the last section.
- Google's infrastructure still understands this trace context. For example, see [this picture](https://user-images.githubusercontent.com/11142171/88596615-769afe00-d033-11ea-90d0-224caa185b11.png). Google Cloud Function's infrastructure is adding in the last span based on this trace context.
- But my actual node-js backend itself does not understand this context, so it doesn't add any other spans.

Can we fix the code to treat a missing `TRACE_TRUE` as 1? I can work on this next week if needed, should be fairly simple.

cc @shivkanya9146, @aabmass

**Comment by aabmass** [comment]
Thanks for the report, this makes sense and we are missing this in python propagator as well.

@kintel could you confirm?

**Comment by kintel** [comment]
`;o=TRACE_TRUE` is optional, but it's probably good to write it as it's usually generated from a trace context, which will have some valid flag setting.

If defaulting any value, it should probably default to zero.

**Comment by nareddyt** [comment]
I agree with your statement for writing the trace context. We should always generate a header that has the flag explicitly set.

But when reading an incoming trace context, we should default to 1.

Otherwise this package will be un-usable for us. We can't easily control how the trace context is generated from other services. It would be much more usable if this package can accommodate propagation with the missing flag.

**Comment by kintel** [comment]
That needs more discussion. Defaulting to 1 can be very unsafe as would imply tracing 100% of requests, and could thus generate a crazy torrent of traces.

Perhaps your use-cases could be discussed in a larger OpenTelemetry forum? W3C traceparent headers don't support as missing sampling decision, so this can become a compatibility challenge.

**Comment by nareddyt** [comment]
That's a fair point.  In that case, I'll try to ensure our callers correctly generate the `;o=1` in the header. That would also resolve my issue with trace context propagation.

We're using the OpenCensus tracer in Envoy proxy to sample requests and generate the header. This code implies it's always included, but we're not seeing that behavior. Need to do more digging into why that's not happening.

https://github.com/census-instrumentation/opencensus-cpp/blob/85e29c4d815171656d54fdf2dc5b74873a4a62bd/opencensus/trace/internal/cloud_trace_context.cc#L104

**Comment by nareddyt** [comment]
It's been a while since I've worked with typescript, but I think the current implementation of the propagator will correct treat a missing `;o=TRACE_TRUE` as `0`.

https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/0c92cdeed2ef080eec547a6be80e5b9c7dbc3d42/packages/opentelemetry-cloud-trace-propagator/src/CloudPropagator.ts#L83

I'll close the issue then, seems like there's no change needed to the propagator (other than clarifying comments about `;o` being optional). Feel free to re-open if you think we should still default to `1`.
