### ISSUE TITLE
Add support for opentelemetry 0.11.0

### ISSUE THREAD

**Issue by sk-** [GoogleCloudPlatform/opentelemetry-operations-js#165]
In #159 the opentelemetry packages were required to be between 0.8 and 0.10, however a day later version 0.11 of the opentelemetry packages was released.

That version has a breaking change as `HttpTextPropagator` was renamed to `TextMapPropagator`. However, given that the opentelemtry packages and these package are still in beta (0.x versions), I'd suggest to keep them in sync.

One could consider having the same versioning scheme while they are both in beta. For example having version `0.11.0` of `@google-cloud/opentelemetry-cloud-trace-propagator` to have a peer dependency on `@opentelemetry/*` `0.11.x`. In that way it's easier to know whether the dependencies are compatible.

**Comment by aabmass** [comment]
Thanks for the overview of breaking changes. I am doing another patch release for the fixed peer deps in #159 then I will work on this.

@mayurkale22, any thoughts on syncing the cloud package versions with the OT versions?

**Comment by confiq** [comment]
This is a great idea! 
This might be nor right place to ask, but right now `@google-cloud/opentelemetry-cloud-trace-propagator` is kinda broken with OT 0.11. 
Any plans to fix the breaking change soon?

**Comment by aabmass** [comment]
Should be able to release tomorrow :)
