### ISSUE TITLE
Some traces are not exported

### ISSUE THREAD

**Issue by DjMilica** [GoogleCloudPlatform/opentelemetry-operations-js#173]
### What version of OpenTelemetry are you using?
I am using 0.10.2 OpenTelemetry version.

### What version of Node are you using?
I am using 12.18.4 node version.

### What did you do?

I'm creating custom instrumentation for my app.
For now, I've created one express middleware where I am starting a new span, and ending it when res.end is called.
My application is on Google Cloud and I am viewing traces on Google Cloud Console platform.
Trace provider is using SimpleSpanProcessor (tried with BatchSpanProcessor also) and TraceExporter (from @google-cloud/opentelemetry-cloud-trace-exporter package).
The problem is that I am not seeing traces for all requests on Google Cloud.
I can see in logs that a new trace is created for every request, but not all are showed in the Trace List.
AlwaysOnSampler is explicitly defined. I also logged "isSpanRecording" option and for every span this option is true.
For example, when I send 5 requests in 10 seconds, in the Trace List I can only see 2 or 3 traces.

### What did you expect to see?
I am expecting to see traces for all incoming requests.

### What did you see instead?
Only 2 or 3 out of 5 request traces are showed.

**Comment by aabmass** [comment]
@DjMilica can you provide some code for a repro?

**Comment by punya** [comment]
Closing out as stale -- please reopen if there are additional details.
