### ISSUE TITLE
Add Cloud Trace exporter in OpenTelemetry registry

### ISSUE THREAD

**Issue by mayurkale22** [GoogleCloudPlatform/opentelemetry-operations-js#18]
Add [Cloud Trace exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/tree/master/packages/opentelemetry-cloud-trace-exporter) in [OpenTelemetry registry](https://opentelemetry.io/registry/). Similar to https://github.com/open-telemetry/opentelemetry.io/pull/107

**Comment by mayurkale22** [comment]
@shivkanya9146 I think you may be interesting in doing this, let me know I can assign to you.

**Comment by mayurkale22** [comment]
Closed via https://github.com/open-telemetry/opentelemetry.io/pull/161, Thank you @shivkanya9146

**Comment by shivkanya9146** [comment]
Done.
