### ISSUE TITLE
Use @grpc/grpc-js instead of grpc

### ISSUE THREAD

**Issue by slowtick** [GoogleCloudPlatform/opentelemetry-operations-js#180]
*Is your feature request related to a problem? Please describe.*
Currently libraries use [grpc package](https://www.npmjs.com/package/grpc). Installing grpc library requires C/C++ compiler and gives errors when native C/C++ is changed/updated.

*Describe the solution you'd like*
Switch to [@grpc/grpc-js package](https://www.npmjs.com/package/@grpc/grpc-js) that is mostly compatible with grpc package while does not require any C/C++ compiler for package install.

*Describe alternatives you've considered*
Sorry, none.

*Additional context*
A handy migration guide available here https://www.npmjs.com/package/@grpc/grpc-js#migrating-from-grpc

**Comment by aabmass** [comment]
Seems like this should be doable. I thought that grpc-js [was not compatible](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/97#discussion_r445935666) with all versions we support, but taking a second look, it should be ok [`^8.13.0 || >=10.10.0`](https://github.com/grpc/grpc-node/blob/a5cc154c8e49cf68691880cbddf33456fbbd306a/packages/grpc-js/package.json#L8-L10).
