### ISSUE TITLE
Handle retry logic and error logging internally

### ISSUE THREAD

**Issue by aabmass** [GoogleCloudPlatform/opentelemetry-operations-js#181]
Context: https://github.com/open-telemetry/opentelemetry-js/issues/1561#issuecomment-703737042

`ExportResult.FAILED_RETRYABLE` will be removed from the OTel JS (https://github.com/open-telemetry/opentelemetry-js/issues/1569) as retries should be handled by the exporter. In addition, the error logging should also be handled in the exporter atm. ~This will fix the `UnhandledPromiseRejectionWarning: undefined` warnings that appear when the metric exporter fails (like when the interval is <5 seconds).~ the `UnhandledPromiseRejectionWarning: undefined` should be fixed but we could add some more specific logging.

**Comment by bkspace** [comment]
@aabmass , any updates on this, appears to be throwing this every time it tries to send traces to Google Trace, which is making logs semi-unreadable.

Are non Googler PRs accepted in this repo?

**Comment by aabmass** [comment]
What are you seeing in your logs exactly?

> Are non Googler PRs accepted in this repo?

PRs are welcome 😄 You just need to sign the CLA!

**Comment by bkspace** [comment]
Gotcha!

When on 0.13.0 (OT core/api), ExportResult.FAILED_RETRYABLE does not exist and an unhandled exception is thrown from a catch block (_batchWriteSpans, trace.js)

Switching to 0.12.0 - we were actually hitting the trace api rate limit 🤒. The BatchSpanProcessor's (which calls export) resultCallback has an empty .catch() block (so any non SUCCESS will have an unhandled exception warning message)

**Comment by aabmass** [comment]
Oh, I didn't realize 0.13.0 was released. The peer dependency in this package is accurate, so it currently only works with 0.12. Let me see how simple updating it is.

> Switching to 0.12.0 - we were actually hitting the trace api rate limit 🤒. The BatchSpanProcessor's (which calls export) resultCallback has an empty .catch() block (so any non SUCCESS will have an unhandled exception warning message)

Got it. 0.13 should fix the unhandled exception

**Comment by damemi** [comment]
@aabmass will open a new issue, original issue is probably resolved but the discussion has brought up new topics

**Comment by aabmass** [comment]
The actual issue I opened this bug for is fixed. I am tracking retries issues in https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/523
