### ISSUE TITLE
Update google-auth-library to ^6.1.1

### ISSUE THREAD

**Issue by abihani-slb** [GoogleCloudPlatform/opentelemetry-operations-js#186]
There's a security vulnerability (CVSS 3 Score: 7.3 | CVSS 2 Score: 7.5) in the [node-forge](https://www.npmjs.com/package/node-forge) npm package, which is a transitive dependency from google-auth-library:

├─┬ @google-cloud/opentelemetry-cloud-trace-exporter
│ └─┬ google-auth-library
│   └─┬ gtoken
│     └─┬ google-p12-pem
│       └── node-forge

node-forge@0.10.0 has a patch for this vulnerability and [google-auth-library@6.1.1](https://github.com/googleapis/google-auth-library-nodejs/blob/master/CHANGELOG.md) has the patch in it.

**Comment by abihani-slb** [comment]
I see there's already a PR open closing this redundant issue.

**Comment by aabmass** [comment]
Thanks for the report!

**Comment by aabmass** [comment]
> node-forge@0.10.0 has a patch for this vulnerability and [google-auth-library@6.1.1](https://github.com/googleapis/google-auth-library-nodejs/blob/master/CHANGELOG.md) has the patch in it.

Unfortunately, that version of `google-auth-library` doesn't support node8 so we would need to drop node8 or get a backport of the fix.
