### ISSUE TITLE
Upgrade to opentelemetry 0.12.0

### ISSUE THREAD

**Issue by sk-** [GoogleCloudPlatform/opentelemetry-operations-js#188]
A new verdion of opentelemetry was released, but because it is a 0.x version it won't get updated unless it is allowed in the dependency file.

See https://github.com/open-telemetry/opentelemetry-js/releases/tag/v0.12.0 for the breaking changes 

I asked about it before, but it would be great to pin the version number of the provided packages to the opentelemetry version, to ease the matching of the packages.

**Comment by aabmass** [comment]
> it would be great to pin the version number of the provided packages to the opentelemetry version, to ease the matching of the packages.

You're suggesting this just for pre GA right?

**Comment by sk-** [comment]
Yes, although that may not be a huge win now, given that opentelemetry is reaching GA soon.

After GA, I'd still keep the versions pinned to the major version, so that version 1.x of opentelemetry-operations uses version 1.x of opentelementry.

Below are my current opentelemetry dependencies
```json
"@google-cloud/opentelemetry-cloud-trace-exporter": "^0.4.1",
"@google-cloud/opentelemetry-cloud-trace-propagator": "^0.4.1",
"@opentelemetry/api": "^0.10.2",
"@opentelemetry/core": "^0.10.2",
"@opentelemetry/node": "^0.10.2",
"@opentelemetry/plugin-express": "^0.9.0",
"@opentelemetry/plugin-grpc-js": "^0.10.2",
"@opentelemetry/plugin-https": "^0.10.2",
"@opentelemetry/tracing": "^0.10.2",
```

Note how all dependencies except for `@opentelemetry/plugin-express`, `@google-cloud/opentelemetry-cloud-trace-exporter` and `@google-cloud/opentelemetry-cloud-trace-propagator` have the same version number, which makes it quite easy to know they have a compatible version.

**Comment by aabmass** [comment]
> After GA, I'd still keep the versions pinned to the major version, so that version 1.x of opentelemetry-operations uses version 1.x of opentelementry.

This make sense for sure, let me bump the version in the PR and see what others think

**Comment by aabmass** [comment]
@sk- I joined the JS SIG call yesterday and they discussed releasing contrib packages more frequently with independent versioning from core. I'm not sure how much value it will have for me to do so. I'm just going to keep it consistent and release at version 0.6.0

When OpenTelemetry goes GA, I will bump to 1.0.0. But if we make any breaking changes to our API, we would have to bump for semconv, regardless of whether or not the OpenTelemetry package has. I don't know how well they can be kept in sync overall 🙁
