### ISSUE TITLE
Add Cloud Monitoring exporter in OpenTelemetry registry

### ISSUE THREAD

**Issue by mayurkale22** [GoogleCloudPlatform/opentelemetry-operations-js#19]
Add [Cloud Monitoring exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/tree/master/packages/opentelemetry-cloud-monitoring-exporter) in [OpenTelemetry registry](https://opentelemetry.io/registry/). Similar to https://github.com/open-telemetry/opentelemetry.io/pull/107

Dependency: [opentelemetry-operations-js/issues/9](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/9)

**Comment by mayurkale22** [comment]
@shivkanya9146 Would you like to take this one?

**Comment by shivkanya9146** [comment]
I will take this issue..

**Comment by mayurkale22** [comment]
closing via https://github.com/open-telemetry/opentelemetry.io/pull/177
