### ISSUE TITLE
http attributes are not mapped accordingly

### ISSUE THREAD

**Issue by sinoohe** [GoogleCloudPlatform/opentelemetry-operations-js#214]
The trace exporter does not export HTTP attributes to a right format compatible with google (https://cloud.google.com/trace/docs/reference/v2/rest/v2/Attributes)

### What version of OpenTelemetry are you using?
0.13.0

### What version of Node are you using?
v14.15.1

### What did you do?
using this code in tracing.js:
```
'use strict';
const {LogLevel, ConsoleLogger} = require('@opentelemetry/core');
const {NodeTracerProvider} = require('@opentelemetry/node');
const {SimpleSpanProcessor} = require('@opentelemetry/tracing');
const {TraceExporter} = require('@google-cloud/opentelemetry-cloud-trace-exporter');
const traceLogger = new ConsoleLogger(LogLevel.DEBUG);
const exporter = new TraceExporter({
  logger: traceLogger
});
const provider = new NodeTracerProvider({logLevel: LogLevel.DEBUG});
provider.addSpanProcessor(new SimpleSpanProcessor(exporter));
provider.register();
```
my package.json:
```
    "@google-cloud/opentelemetry-cloud-trace-exporter": "0.7.0",
    "@opentelemetry/tracing": "0.13.0",
    "@opentelemetry/core": "0.13.0",
    "@opentelemetry/node": "0.13.0",
    "@opentelemetry/plugin-http": "0.13.0",
    "@opentelemetry/plugin-https": "0.13.0",
    "@opentelemetry/plugin-mongodb": "0.11.0"
```
I started my HTTP server and created some GET and POST requests to the server.

### What did you expect to see?
I expected to see `/http/method` and `/http/status_text` as labels

### What did you see instead?
But I see 
![Screenshot from 2020-12-16 11-08-03](https://user-images.githubusercontent.com/350684/102318884-47a80900-3f8f-11eb-8ac2-70a7ff13eab2.png)

### Related ticket
It seems that the issue is fixed in https://github.com/census-instrumentation/opencensus-node/issues/651 but not in this repository.
### Suggestion:
expose a method on the exporter so I can define my own mapping and change the attribute name of each propery that is important for me. for example like this:
```
const exporter = new TraceExporter({
  customMapping: (fieldName) => {
    const regex = /\./gi;
    return '/'+fieldName.replaceAll(regex, '/');
  }
});
```

**Comment by loneparadox** [comment]
I could find the following go and python exporter implementations. 
It seems to have a conversation like this in
See https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/540edb3af1732e2795bf251d89a57cf9350d5441/exporter/trace/trace_proto.go#L52
and https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/c3772de4cf50950f1d51685ff3bbf0e46ee026df/opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py#L371
