### ISSUE TITLE
Cannot read property 'FAILED_RETRYABLE' of undefined

### ISSUE THREAD

**Issue by sinoohe** [GoogleCloudPlatform/opentelemetry-operations-js#215]
getting 
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'FAILED_RETRYABLE' of undefined` on the console

### What version of OpenTelemetry are you using?
0.13.0

### What version of Node are you using?
v14.15.1

### What did you do?
follow up instructions on https://github.com/GoogleCloudPlatform/opentelemetry-operations-js#readme to create tracing.js file
run the project by this command: `node -r ./tracing.js index.js`
sending some curl requests to the server:
`curl --location --request GET 'http://localhost:3000'`

### What did you expect to see?
I expected to not have any warning messages

### What did you see instead?
```
(node:13140) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'FAILED_RETRYABLE' of undefined
    at TraceExporter._batchWriteSpans (/home/mehran/projects/some-sample-project/node_modules/@google-cloud/opentelemetry-cloud-trace-exporter/build/src/trace.js:91:40)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async TraceExporter.export (/home/mehran/projects/some-sample-project/node_modules/@google-cloud/opentelemetry-cloud-trace-exporter/build/src/trace.js:61:24)
(node:13140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

### Sample Project
[some-sample-project.zip](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/files/5701372/some-sample-project.zip)
steps:
- npm install
- change values in tracing.js for your own(`projectId`, `keyFile`, `keyFileName`)
- run `node -r ./tracing.js index.js`
- run `curl --location --request GET 'http://localhost:3000'`
- you should see the warning logs after a few seconds

**Comment by aleccool213** [comment]
I was getting this when I upgraded to 0.13.0, needed to downgrade 0.12.0 to fix this. Likely this pr will fix: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/277

**Comment by vmarchaud** [comment]
@aleccool213 Sadly the PR will not fix that, it's linked to this breaking change: https://github.com/open-telemetry/opentelemetry-js/commit/14c92dabfc735117bec2350d30ea009766089518, the google export should stop using `FAILED_RETRYABLE` for you to be able to use `0.13.0` without issue.

**Comment by aabmass** [comment]
https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/208 upgrades this repo packages for 0.13.0, trying to get it reviewed and merged soon

**Comment by aabmass** [comment]
Btw, the `peerDependencies` are all correct in these packages. If you run `npm ls`, you should see this or something similar if you have installed an unsupported opentelemetry version:

```
npm ERR! peer dep missing: @opentelemetry/tracing@^0.12.0, required by @google-cloud/opentelemetry-cloud-trace-exporter@0.7.0
npm ERR! peer dep missing: @opentelemetry/api@^0.12.0, required by @google-cloud/opentelemetry-cloud-trace-exporter@0.7.0
npm ERR! peer dep missing: @opentelemetry/core@^0.12.0, required by @google-cloud/opentelemetry-cloud-trace-exporter@0.7.0
npm ERR! peer dep missing: @opentelemetry/resources@^0.12.0, required by @google-cloud/opentelemetry-cloud-trace-exporter@0.7.0
```

**Comment by chrisdostert** [comment]
Is it possible to get a release cut including this?
