### ISSUE TITLE
Was not able to determine GCP project ID

### ISSUE THREAD

**Issue by kaareal** [GoogleCloudPlatform/opentelemetry-operations-js#224]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
0.8

### What version of Node are you using?
v14.15.0

### What did you do?
I updated @google-cloud/opentelemetry-cloud-trace-exporter to 0.8
And ran my code on a local machine (outside google cloud) 

### What did you expect to see?
No error

### What did you see instead?
```
Error: Was not able to determine GCP project ID
  at TraceExporter.export (/service/node_modules/@google-cloud/opentelemetry-cloud-trace-exporter/build/src/trace.js:56:24)
   at processTicksAndRejections (internal/process/task_queues.js:93:5)

Was not able to determine GCP project ID
```

### Additional context

```
const { TraceExporter } = require('@google-cloud/opentelemetry-cloud-trace-exporter');

const provider = new NodeTracerProvider({});
// Configure the span processor to send spans to the exporter
provider.addSpanProcessor(new SimpleSpanProcessor(new TraceExporter()));
provider.register();
```
Triggers no error under 0.7 but throws error under 0.8

**Comment by aabmass** [comment]
What exact version of `google-auth-library` are you seeing resolved when you switch between these versions? Both `@google-cloud/opentelemetry-cloud-trace-exporter` 0.7.0 and 0.8.0 have the same `"google-auth-library": "^6.1.3"` which is where this would be coming from.

Regardless, just passing the project ID to the exporter constructor or setting `GOOGLE_CLOUD_PROJECT` environment variable should fix this

**Comment by punya** [comment]
Closing out as stale -- please reopen if there are additional details.
