### ISSUE TITLE
TypeError: batchWriteSpans error: api_1.getParentSpanContext is not a function

### ISSUE THREAD

**Issue by QuestionAndAnswer** [GoogleCloudPlatform/opentelemetry-operations-js#231]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
"@google-cloud/opentelemetry-cloud-trace-exporter": "^0.8.0"
"@google-cloud/opentelemetry-cloud-trace-propagator": "^0.8.0"
"@opentelemetry/api": "^0.16.0",
"@opentelemetry/node": "^0.16.0",
"@opentelemetry/plugin-express": "^0.13.0",
"@opentelemetry/plugin-grpc-js": "^0.16.0",
"@opentelemetry/plugin-http": "^0.16.0",
"@opentelemetry/plugin-https": "^0.16.0",
"@opentelemetry/plugin-redis": "^0.13.0",
"@opentelemetry/resources": "^0.16.0",
"@opentelemetry/tracing": "^0.16.0",

### What version of Node are you using?
12.18.3

### What did you do?
Cloud propagator use.

```typescript
import { NoopLogger } from "@opentelemetry/api";
import { TraceExporter } from "@google-cloud/opentelemetry-cloud-trace-exporter";
import { CloudPropagator } from '@google-cloud/opentelemetry-cloud-trace-propagator';
import { NodeTracerProvider } from "@opentelemetry/node";
import { SimpleSpanProcessor } from "@opentelemetry/tracing";
import { Resource } from '@opentelemetry/resources';

function startTracing () {
    const provider = new NodeTracerProvider({
        plugins: {
            http: {
            }
        },
        resource: new Resource({
        }),
    });

    const exporter = new TraceExporter({
        logger: new NoopLogger(),
    });

    provider.addSpanProcessor(new SimpleSpanProcessor(exporter));

    provider.register({
        // Required until we have @google-cloud/trace in the other services
        propagator: new CloudPropagator()
    });
}

startTracing();
```

### What did you expect to see?
No errors.

### What did you see instead?
Error after I started service and it OPTL finished plugins loading. When it reaching CloudPropagator inject call, this error appears.

```
{
    "stack": "TypeError: batchWriteSpans error: api_1.getParentSpanContext is not a function\n    at CloudPropagator.inject (D:\\Projects\\app\\services\\service1\\node_modules\\@google-cloud\\opentelemetry-cloud-trace-propagator\\build\\src\\CloudPropagator.js:39:35)\n    at PropagationAPI.inject (D:\\Projects\\app\\services\\service1\\node_modules\\@opentelemetry\\api\\build\\src\\api\\propagation.js:56:44)\n    at setSpanContext (D:\\Projects\\app\\services\\service1\\node_modules\\@opentelemetry\\plugin-grpc-js\\build\\src\\client\\utils.js:188:23)\n    at D:\\Projects\\app\\services\\service1\\node_modules\\@opentelemetry\\plugin-grpc-js\\build\\src\\client\\utils.js:108:9\n    at D:\\Projects\\app\\services\\service1\\node_modules\\@opentelemetry\\plugin-grpc-js\\build\\src\\client\\utils.js:59:146\n    at AsyncHooksContextManager.with (D:\\Projects\\app\\services\\service1\\node_modules\\@opentelemetry\\context-async-hooks\\build\\src\\AsyncHooksContextManager.js:42:20)\n    at ContextAPI.with (D:\\Projects\\app\\services\\service1\\node_modules\\@opentelemetry\\api\\build\\src\\api\\context.js:60:46)\n    at ServiceClientImpl.clientMethodTrace [as BatchWriteSpans] (D:\\Projects\\app\\services\\service1\\node_modules\\@opentelemetry\\plugin-grpc-js\\build\\src\\client\\utils.js:59:38)\n    at internal/util.js:297:30\n    at new Promise (<anonymous>)\n    at ServiceClientImpl.clientMethodTrace (internal/util.js:296:12)\n    at TraceExporter._batchWriteSpans (D:\\Projects\\app\\services\\service1\\node_modules\\@google-cloud\\opentelemetry-cloud-trace-exporter\\build\\src\\trace.js:87:19)\n    at async TraceExporter.export (D:\\Projects\\app\\services\\service1\\node_modules\\@google-cloud\\opentelemetry-cloud-trace-exporter\\build\\src\\trace.js:64:24)",
    "message": "batchWriteSpans error: api_1.getParentSpanContext is not a function",
    "name": "TypeError",
    "toJSON": "function () {\r\n        let err = {};\r\n        Object.getOwnPropertyNames(this).forEach(function (key) {\r\n            err[key] = this[key];\r\n        }, this);\r\n        return err;\r\n    }"
}
```

### Additional context
I tracked down the issue. This is due to OPTL not following the semver.

Current version (0.8.0) of cloud propagator relies on ^0.14.0 of @opentelemetry/api package version which, has getParentSpanContext method exported.

[https://github.com/open-telemetry/opentelemetry-js/blob/v0.14.0/packages/opentelemetry-api/src/context/context.ts#L80](https://github.com/open-telemetry/opentelemetry-js/blob/v0.14.0/packages/opentelemetry-api/src/context/context.ts#L80)

But, @opentelemetry/api seems like not following the semantic versioning and made a breaking change within a 0.16.0 version, and now they using getSpanContext method instead.

[https://github.com/open-telemetry/opentelemetry-js/blob/v0.16.0/packages/opentelemetry-api/src/context/context.ts#L76](https://github.com/open-telemetry/opentelemetry-js/blob/v0.16.0/packages/opentelemetry-api/src/context/context.ts#L76)

For the 0.8.0 propagator package version it needs to update it's calls to match 0.16.0 version of @opentelemetry/api.

Yes, it was from 0.14.0 to 0.15.0 update.
[https://github.com/open-telemetry/opentelemetry-js#0140-to-0150](https://github.com/open-telemetry/opentelemetry-js#0140-to-0150)

**Comment by aabmass** [comment]
> For the 0.8.0 propagator package version it needs to update it's calls to match 0.16.0 version of @opentelemetry/api.

Thanks for reporting. Yes, this package needs to be updated and won't work with 0.16.0 right now. The peerDependency for the package is `^0.14.0` which is still correct https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/10b37fbcb920a7bc68efd6bf97db5084b32e5085/packages/opentelemetry-cloud-trace-propagator/package.json#L57-L58

If you run `npm ls`, do you see npm complain about "unmet peer dependencies"?

> But, @opentelemetry/api seems like not following the semantic versioning and made a breaking change within a 0.16.0 version, and now they using getSpanContext method instead.

I don't believe they have broken semver, because the major version is still 0, which means each minor version is incompatible.

**Comment by QuestionAndAnswer** [comment]
> I don't believe they have broken semver, because the major version is still 0, which means each minor version is incompatible.

@aabmass well, I guess you confusing something. [https://semver.org/](https://semver.org/). With any incompatible change major version should be updated, and API change is an breaking change, so it's not enough to update only minor. Otherwise, they should've kept getParentSpanContext and added getSpanContext, so nothing is broken.

> If you run npm ls, do you see npm complain about "unmet peer dependencies"?

No, and I don't think it should, as actually 0.16.0 following semver is a compatible version for ^0.14.0 selector.

![image](https://user-images.githubusercontent.com/6842709/107479453-2e38cd00-6b8c-11eb-91ab-5acae7ae00a3.png)

**Comment by QuestionAndAnswer** [comment]
Oh, I looked through the dependencies versions of whole opentelemetry stack, and for 0.16.0 version it's a mess. I'm downgrading to 0.14.0, for api, core and the plugins, as they all correctly sticking single 0.14.0 version. 0.16.0 packages somehwere using 0.16.0, somewhere 0.15.0, and hence crating lots of issues.

**Comment by aabmass** [comment]
@QuestionAndAnswer there's an edge case in semver for major version zero https://semver.org/#spec-item-4

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Npm actually respects this ([try it here](https://semver.npmjs.com/))
<img width="1082" alt="Screen Shot 2021-02-10 at 11 06 29 AM" src="https://user-images.githubusercontent.com/1510004/107536681-0a778600-6b90-11eb-85a9-55d42ba0d92f.png">

Here's what I get when I tried your dependencies:

```sh
aaronabbott@aaronabbott:~/tmp/npmtmp$ cat package.json
{
  "name": "npmtmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@google-cloud/opentelemetry-cloud-trace-exporter": "^0.8.0",
    "@google-cloud/opentelemetry-cloud-trace-propagator": "^0.8.0",
    "@opentelemetry/api": "^0.16.0",
    "@opentelemetry/node": "^0.16.0",
    "@opentelemetry/plugin-express": "^0.13.0",
    "@opentelemetry/plugin-grpc-js": "^0.16.0",
    "@opentelemetry/plugin-http": "^0.16.0",
    "@opentelemetry/plugin-https": "^0.16.0",
    "@opentelemetry/plugin-redis": "^0.13.0",
    "@opentelemetry/resources": "^0.16.0",
    "@opentelemetry/tracing": "^0.16.0"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
aaronabbott@aaronabbott:~/tmp/npmtmp$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: npmtmp@1.0.0
npm ERR! Found: @opentelemetry/api@0.16.0
npm ERR! node_modules/@opentelemetry/api
npm ERR!   @opentelemetry/api@"^0.16.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @opentelemetry/api@"^0.14.0" from @google-cloud/opentelemetry-cloud-trace-exporter@0.8.0
npm ERR! node_modules/@google-cloud/opentelemetry-cloud-trace-exporter
npm ERR!   @google-cloud/opentelemetry-cloud-trace-exporter@"^0.8.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /usr/local/google/home/aaronabbott/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/google/home/aaronabbott/.npm/_logs/2021-02-10T16_11_51_358Z-debug.log
aaronabbott@aaronabbott:~/tmp/npmtmp$
```

**Comment by QuestionAndAnswer** [comment]
@aabmass , well, okay. Good to know. My install didn't throw me this. Don't know what's next. Either update exporter to work with 0.16.0 of an api package or close the ticket if it's not under the repo support policy.

Thanks for replies.

**Comment by aabmass** [comment]
Might be npm version, I'm not sure. It will be updated for 0.16.0 anyway :) (#232)
