### ISSUE TITLE
Add support for 0.17 opentelemetry-js package

### ISSUE THREAD

**Issue by weyert** [GoogleCloudPlatform/opentelemetry-operations-js#235]
*Is your feature request related to a problem? Please describe.*
A new version of the `opentelemetry`-package has been release version v0.17

*Describe the solution you'd like*
Update the package to depend on v0.17 instead of v0.16

*Additional context*
None

**Comment by aabmass** [comment]
Thanks for the heads up, should be able to get to it tomorrow or Wednesday.

**Comment by weyert** [comment]
Any news 👼 ?

**Comment by weyert** [comment]
@aabmass I have a draft pull request to upgrade to 0.17+ only I am having trouble with the `request`-parameter and its `auth`-property in the monitoring exporter. If you know a solution for that would be great!

**Comment by aabmass** [comment]
Thanks for the PR, I'll comment on it :)
