### ISSUE TITLE
Missing 0.90 in releases

### ISSUE THREAD

**Issue by weyert** [GoogleCloudPlatform/opentelemetry-operations-js#247]
Looks like no new release was made for Github releases, see: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/tag/v0.8.0

**Comment by aabmass** [comment]
Oops, forgot to publish it, here it is https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/tag/v0.9.0. Thanks for letting me know

**Comment by weyert** [comment]
Thank you :)
