### ISSUE TITLE
core_1.ExportResultCode does not exist

### ISSUE THREAD

**Issue by thespacedeck** [GoogleCloudPlatform/opentelemetry-operations-js#252]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
^0.9.0

### What version of Node are you using?
v12.19.1

### What did you do?
If possible, provide a recipe for reproducing the error.
```
const opentelemetry = require("@opentelemetry/api");
const { TraceExporter } = require('@google-cloud/opentelemetry-cloud-trace-exporter');
const { NodeTracerProvider } = require("@opentelemetry/node");
const { BatchSpanProcessor } = require("@opentelemetry/tracing");

const provider = new NodeTracerProvider();
provider.register();

const exporter = new TraceExporter();

provider.addSpanProcessor(new BatchSpanProcessor(exporter));

--->
const span = tracer.startSpan().updateName("new_span");
...run logic...
span.end()
```

### What did you expect to see?
Expected no error

### What did you see instead?
TypeError: Cannot read property 'FAILED' of undefined
/@google-cloud/opentelemetry-cloud-trace-exporter/build/src/trace.js:95:52)

relates to ln 92 error.message => Cannot read property 'SUCCESS' of undefined

### Additional context
I think core_1.ExportResultCode does not exist, only core_1.ExportResult does.

core_1.ExportResult looks like this: 
{
  '0': 'SUCCESS',
  '1': 'FAILED_NOT_RETRYABLE',
  '2': 'FAILED_RETRYABLE',
  SUCCESS: 0,
  FAILED_NOT_RETRYABLE: 1,
  FAILED_RETRYABLE: 2
}

**Comment by weyert** [comment]
Make sure you are using 0.18+ of Opentelemetry-js based on the error it looks like you are using an older version

**Comment by aabmass** [comment]
Adding onto that, what version of npm are you using @thespacedeck ? If you have npm 7, it should have complained to you about unsupported peerDependency

**Comment by weyert** [comment]
Just wanted to let you know a new version of pubsub package got published earlier today
