### ISSUE TITLE
MetricExporter.export signature doesn't match the base class

### ISSUE THREAD

**Issue by seanachai** [GoogleCloudPlatform/opentelemetry-operations-js#254]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
@opentelemetry/metrics: ^0.18.2
@google-cloud/opentelemetry-cloud-monitoring-exporter: ^0.9.0

### What version of Node are you using?
v12.20.2

### What did you do?
If possible, provide a recipe for reproducing the error.

The MetricExporter implementation's export definition does not match the base class it's implementing. The base class signature does not return a Promise<void>. However, there is an [open issue](https://github.com/open-telemetry/opentelemetry-js/issues/1023) to support returning a promise. Having these functions not match up causes a Typescript compilation issue and ignoring it causes a dangling promise error. 

I'm referencing line 94 in [packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/103e0a4426560bd9a8cc932af2f03a889f2bd1fe/packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts#L94):

```
async export(
    metrics: MetricRecord[],
    cb: (result: ExportResult) => void
  ): Promise<void> {
```

The base class is [MetricExporter from opentelemetry/opentelemetry-metrics](https://github.com/open-telemetry/opentelemetry-js/blob/897c35f497363ee3f3ea4c1e5ad1628e09ec9041/packages/opentelemetry-metrics/src/export/types.ts#L95):

```
export interface MetricExporter {
  /** Exports the list of a given {@link MetricRecord} */
  export(
    metrics: MetricRecord[],
    resultCallback: (result: ExportResult) => void
  ): void;

  /** Stops the exporter. */
  shutdown(): Promise<void>;
}
```

**Comment by aabmass** [comment]
> Having these functions not match up causes a Typescript compilation issue

This is valid in TS (see [here](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void) and [this repro](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyEAHgA7pRgAUBydyAthGFMAgM4Bcy7LoA5gG0AugBpa9BACNuVKBHYBXADZhuvViH4BKZAF4AfMgBu6YABMJ27qYsBuAgF8CBBMrjt2yAEJwoyYAZSZQgmcC8MLDxCZA8ATxAEIjIKagk6Jj4OdT4tEXEYumlZeSVVHM0dfSNbSxjrZAAFKHQGYHYIAB5ao2i6Z3xHIA)) so it should compile.

> and ignoring it causes a dangling promise error.

By dangling promise error, I'm assuming you mean `UnhandledPromiseRejectionWarning`? I see your point here, we should probably wrap the inside function to handle rejection. PRs welcome if you have the time 😄

**Comment by seanachai** [comment]
Oh ok well that's interesting haha. Admittedly, I'm new to TS so thanks for your help here @aabmass.

Here's the error I'm getting when I run `tsc metrics.ts` where metrics.ts is the following:
```
import { MeterProvider } from '@opentelemetry/metrics';
import { MetricExporter } from '@google-cloud/opentelemetry-cloud-monitoring-exporter';

const exporter = new MetricExporter();

// Register the exporter
const meter = new MeterProvider({
  exporter,
  interval: 60000,
}).getMeter('example-meter');
```

Error: 
```
error TS2322: Type 'import("/Users/seanachai/workspace/example/node_modules/@google-cloud/opentelemetry-cloud-monitoring-exporter/build/src/monitoring").MetricExporter' is not assignable to type 'import("/Users/seanachai/workspace/example/node_modules/@opentelemetry/metrics/build/src/export/types").MetricExporter'.
  Types of property 'export' are incompatible.
    Type '(metrics: MetricRecord[], cb: (result: ExportResult) => void) => Promise<void>' is not assignable to type '(metrics: MetricRecord[], resultCallback: (result: ExportResult) => void) => void'.
      Types of parameters 'cb' and 'resultCallback' are incompatible.
        Types of parameters 'result' and 'result' are incompatible.
          Type 'import("/Users/seanachai/workspace/example/node_modules/@opentelemetry/core/build/src/ExportResult").ExportResult' is not assignable to type 'import("/Users/seanachai/workspace/example/node_modules/@opentelemetry/metrics/node_modules/@opentelemetry/core/build/src/ExportResult").ExportResult'.

8   exporter,
```

For the dangling promise issue - yeah I believe it's `UnhandledPromiseRejectionWarning` that I'm seeing. I'd be happy to help with a PR for that. 🍻

**Comment by aabmass** [comment]
Based on this from your error message:

>         Types of parameters 'result' and 'result' are incompatible.

I would guess that this is version mismatch problem where TS is getting incompatible `ExportResult` classes between interface and impl. Could you share a package.json to repro this, just to confirm? Also what version of npm do you see from `npm --version`?
