### ISSUE TITLE
propagator: allow setting of TRACE_TRUE when not present

### ISSUE THREAD

**Issue by naseemkullah** [GoogleCloudPlatform/opentelemetry-operations-js#257]
https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/103e0a4426560bd9a8cc932af2f03a889f2bd1fe/packages/opentelemetry-cloud-trace-propagator/src/CloudPropagator.ts#L89-L93

Would it make sense to have an option to add a sampling decision if TRACE_TRUE != 1?

use case: external clients are not tracing aware/instrumented, but I would like the HTTPS LB => backend service span if possible/feasible.

Currently TRACE_TRUE is never defined AFAICT

**Comment by naseemkullah** [comment]
e.g. (notice `NEWTHING`):

```
 traceFlags: 
   isNaN(Number(matches[3])) || matches[3] === '0' 
     ? NEWTHING ?? TraceFlags.NONE 
     : TraceFlags.SAMPLED,
 ```

**Comment by aabmass** [comment]
Not sure I understand the question here. `TraceFlags` only has two possible values, what would `NEWTHING` be?

**Comment by naseemkullah** [comment]
Ah sorry, NEWTHING would be a sampling algorithm to select `TraceFlags.NONE` or `TraceFlags.SAMPLED`

**Comment by aabmass** [comment]
> Where `getSampledOrNoneFromSampler()` returns `TraceFlags.NONE` or `TraceFlags.SAMPLED` based on some probability.

I think the best way to achieve something like this is to set a `ParentBasedSampler` with a [`remoteParentNotSampled`](https://github.com/open-telemetry/opentelemetry-js/blob/a2fff0dd2ece0c7d1246d5dae142fcf03371c21e/packages/opentelemetry-core/src/trace/sampler/ParentBasedSampler.ts#L135-L136) like:
```ts
new ParentBasedSampler({
  remoteParentNotSampled: new TraceIdRatioBasedSampler(1 / X),
});
```

That would achieve what you're proposing right?

**Comment by naseemkullah** [comment]
> > Where `getSampledOrNoneFromSampler()` returns `TraceFlags.NONE` or `TraceFlags.SAMPLED` based on some probability.
> 
> I think the best way to achieve something like this is to set a `ParentBasedSampler` with a [`remoteParentNotSampled`](https://github.com/open-telemetry/opentelemetry-js/blob/a2fff0dd2ece0c7d1246d5dae142fcf03371c21e/packages/opentelemetry-core/src/trace/sampler/ParentBasedSampler.ts#L135-L136) like:
> 
> ```ts
> new ParentBasedSampler({
>   remoteParentNotSampled: new TraceIdRatioBasedSampler(1 / X),
> });
> ```
> 
> That would achieve what you're proposing right?

If I'm not mistaken, I don't think it would include the parent span, which is the span from HTTPS LB to backend service, which is my goal.

**Comment by aabmass** [comment]
Ahh, if the load balancer isn't sending any spans, there is nothing you can do about it in the OTel config. OTel doesn't back-propagate in response headers at the moment, and I don't think that X-Cloud-Trace-Context is valid for that purpose.

**Comment by aabmass** [comment]
From Slack:

> I'm confused about parent based sampler. I have a remote parent (load balancer) whose trace flags are always set to off, yet the rest of the trace composed of otel instrumented services with parent based sampler (and trace id ratio sampler as its root) is sampled. Finally, the load balancer's trace id is carried through, but it's span is missing.
> 
> ```ts
> new ParentBasedSampler({
>             root: new TraceIdRatioBasedSampler(otelSamplingProbability),
>          })
>```

With that OTel sampler config, when `X-Cloud-Trace-Context` is not explicitly sampling (`o=1`), you should not be seeing **any** spans in that trace coming through.. If that's not the case, that would be an OTel JS SDK issue.

**Comment by naseemkullah** [comment]
> From Slack:
> 
> > I'm confused about parent based sampler. I have a remote parent (load balancer) whose trace flags are always set to off, yet the rest of the trace composed of otel instrumented services with parent based sampler (and trace id ratio sampler as its root) is sampled. Finally, the load balancer's trace id is carried through, but it's span is missing.
> > ```ts
> > new ParentBasedSampler({
> >             root: new TraceIdRatioBasedSampler(otelSamplingProbability),
> >          })
> > ```
> 
> With that OTel sampler config, when `X-Cloud-Trace-Context` is not explicitly sampling (`o=1`), you should not be seeing **any** spans in that trace coming through.. If that's not the case, that would be an OTel JS SDK issue.

That's true, I will open an issue in the otel js repo after reproducing locally.

That aside:

>  there is nothing you can do about it in the OTel config. OTel doesn't back-propagate in response headers at the moment, and I don't think that X-Cloud-Trace-Context is valid for that purpose.

This comes back to the option I am proposing, allowing cloud trace propagator to enabled sampling at the HTTPS LB level if not explicitly set (i.e. `o is nullish`).  To circle back to the use case: while the external client may not be trace-instrumented, to still measure the span between the LB and the backend service. WDYT?

**Comment by aabmass** [comment]
> allowing cloud trace propagator to enabled sampling at the HTTPS LB level if not explicitly set

I still don't exactly understand, how would you achieve this at the HTTPS LB level if it is within your JS code *after* the LB?

**Comment by aabmass** [comment]
Ya, I believe the approach I mentioned in https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/257#issuecomment-816796572 should do exactly that for the current process and any calls after. However the root span from GCLB will still not be sent unless `o=1` in the incoming request AFAIK.

> HTTPS LB include the cloud trace context but without any `o`/`TRACE_TRUE`

Are you sure it is never sending `o=1`? It might just be sampling at a low ratio. You could try forcing it to be sampled in the request to the LB ([per these instructions](https://cloud.google.com/trace/docs/setup#force-trace:~:text=For%20example%2C%20to%20force%20a%20trace%20with%20curl%3A)) and see if it passes the `o=1` on to your JS service?

**Comment by naseemkullah** [comment]
> Ya, I believe the approach I mentioned in [#257 (comment)](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/257#issuecomment-816796572) should do exactly that for the current process and any calls after. However the root span from GCLB will still not be sent unless `o=1` in the incoming request AFAIK.

I am interested in the span from HTTPS LB to first backend service, what you mention would allow for the remainder of the trace to be sampled (which is already happening strangely without setting the `remoteParentNotSampled` strangely, but that is off topic).

Right `o=1` is never set and forcing it indeed samples the whole trace.

Is there something wrong with the approach of setting the `o` via the propagator when unset?

**Comment by aabmass** [comment]
Where is this screenshot coming from?

**Comment by naseemkullah** [comment]
> Where is this screenshot coming from?

Jaeger UI.

curl with or without trace context => HTTPS LB (trace context added if none present) => otel instrumented backend svc => otel collector => jaeger

**Comment by aabmass** [comment]
Ahh that makes a lot of sense, I thought you were exporting traces to Google Cloud Trace. The problem is that none of the spans from GCLB are sent to Jaeger, they only appear in Cloud Trace.

**Comment by naseemkullah** [comment]
Oh yeah that does, thanks! I guess there is no way to achieve exporting GCP infra spans to something other than Cloud Trace. As such there will always be missing spans if trying to capture those and using a backend other than Cloud Trace, is that right?

**Comment by aabmass** [comment]
For now, unfortunately yes there will be missing spans, but those spans should still be available in Cloud Trace if you can find a way to easily link them ([link patterns](https://www.jaegertracing.io/docs/1.22/frontend-ui/#link-patterns)?).

**Comment by aabmass** [comment]
Can we close this issue @naseemkullah?

**Comment by naseemkullah** [comment]
Absolutely, thanks for the help!!
