### ISSUE TITLE
Modify /http/host or http.url

### ISSUE THREAD

**Issue by devyourcar** [GoogleCloudPlatform/opentelemetry-operations-js#271]
Hi there,

I would like to mask certain query params that are part of the request url (e.g. token / auth).
How would I go about updating those attributes via @google-cloud/opentelemetry-cloud-trace-exporter so they don't show up in the Google Trace labels section?

Thanks.

**Comment by aabmass** [comment]
Can you share a little more info about how the traces are being created? Are you using one of the instrumentation packages from OpenTelemetry?
