### ISSUE TITLE
cloud-trace-exporter not sending spans with update of @opentelemetry dependencies to 0.20.0

### ISSUE THREAD

**Issue by benitezho** [GoogleCloudPlatform/opentelemetry-operations-js#273]
### What version of OpenTelemetry are you using?
Latest version 0.20.0

### What version of Node are you using?
v12.16.1

### What did you do?
Upgraded opentelemetry dependencies to latest release 0.20.0

> "@google-cloud/opentelemetry-cloud-trace-exporter": "0.9.0",
   "@opentelemetry/api": "^0.20.0",
   "@opentelemetry/core": "^0.20.0",
   "@opentelemetry/metrics": "^0.20.0",
   "@opentelemetry/node": "^0.20.0",
   "@opentelemetry/resources": "^0.20.0",
   "@opentelemetry/tracing": "^0.20.0",

### What did you expect to see?
Traces sent normally.

### What did you see instead?
spanId and traceId are not setted correctly, an there is an error on trace.js file, method *async export*, line 64 `const result = await this._batchWriteSpans(namedSpans);`, 

Displayed error its:
`{
  "code": 1,
  "error": {
    "code": 3,
    "details": "Invalid trace name: Trace ID must be a hexadecimal number with size = 32. Current Trace ID = undefined",
    "metadata": {
      "internalRepr": {},
      "options": {}
    }
  }
}
`

### Additional context
On file *transform.js* method *getReadableSpanTransformer*, lines 38, 39 and 40, spanContext has been renamed to _spanContext on @opentelemetry/tracing
> name: `projects/${projectId}/traces/${span.spanContext.traceId}/spans/${span.spanContext.spanId}`,
    spanId: span.spanContext.spanId,
    sameProcessAsParentSpan: { value: !span.spanContext.isRemote },

**Comment by aabmass** [comment]
PR for supporting 0.20 is in the works. However, NPM should have complained about unmet peer dependencies because 0.20 is not supported with the current release. Do you mind sharing your package.json file?

**Comment by benitezho** [comment]
@aabmass yes, npm it's complaining about the peer dependencies. 

> warning " > @google-cloud/opentelemetry-cloud-trace-exporter@0.9.0" has incorrect peer dependency "@opentelemetry/api@^0.18.0".
    warning " > @google-cloud/opentelemetry-cloud-trace-exporter@0.9.0" has incorrect peer dependency "@opentelemetry/core@^0.18.0".
   warning " > @google-cloud/opentelemetry-cloud-trace-exporter@0.9.0" has incorrect peer dependency "@opentelemetry/resources@^0.18.0".
   warning " > @google-cloud/opentelemetry-cloud-trace-exporter@0.9.0" has incorrect peer dependency "@opentelemetry/tracing@^0.18.0".

If the update to @opentelemetry 0.20.0 its in WIP, then this its not a bug, sorry for the inconvenience.

**Comment by Flydiverny** [comment]
Also ran into this after following gcp tutorials on setting up tracing and was very confused why things where not working 😄 Any chance for a release of the fixes in #274?

**Comment by weyert** [comment]
@Flydiverny I was told it might be release on Monday 🤞

**Comment by aabmass** [comment]
#291 is queued up and ready to go (waiting for review). Be aware there are a few breaking changes in the output of the traces
