### ISSUE TITLE
Was not able to determine GCP project ID 

### ISSUE THREAD

**Issue by thanaratjaruenying** [GoogleCloudPlatform/opentelemetry-operations-js#302]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
`"@google-cloud/opentelemetry-cloud-trace-exporter": "0.10.0"`
`"@opentelemetry/node": "0.23.0"`
`"@opentelemetry/tracing": "0.23.0"`

### What version of Node are you using?
`v12.22.1`

### What did you do?
```
*MY_GCP_CREDENTIALS contains project id*
const exporter =  new TraceExporter({ credentials: MY_GCP_CREDENTIALS })
provider.addSpanProcessor(new BatchSpanProcessor(exporter))
```

### What did you expect to see?
I expect not to see errors

### What did you see instead?
```
{"stack":"Error: Was not able to determine GCP project ID\n    at TraceExporter.export (node_modules/@google-cloud/opentelemetry-cloud-trace-exporter/build/src/trace.js:56:24)\n    at /node_modules/@opentelemetry/tracing/build/src/export/BatchSpanProcessorBase.js:130:38\n    at AsyncHooksContextManager.with (node_modules/@opentelemetry/context-async-hooks/build/src/AsyncHooksContextManager.js:42:23)\n    at ContextAPI.with (
node_modules/@opentelemetry/api/build/src/api/context.js:71:54)\n    at node_modules/@opentelemetry/tracing/build/src/export/BatchSpanProcessorBase.js:126:31\n    at new Promise (<anonymous>)\n    at BatchSpanProcessor._flushOneBatch (node_modules/@opentelemetry/tracing/build/src/export/BatchSpanProcessorBase.js:120:16)\n    at Timeout.<anonymous> (node_modules/@opentelemetry/tracing/build/src/export/BatchSpanProcessorBase.js:147:18)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers (internal/timers.js:497:7)","message":"Was not able to determine GCP project ID","name":"Error"}
```

**Comment by aabmass** [comment]
> ```
> *MY_GCP_CREDENTIALS contains project id*
> const exporter =  new TraceExporter({ credentials: MY_GCP_CREDENTIALS })
> provider.addSpanProcessor(new BatchSpanProcessor(exporter))
> ```

The credentials object shouldn't have project ID. You can pass the project ID directly in the options: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/b80a2b6fd17dc9fce74b2aad4bc19e97dba8f286/packages/opentelemetry-cloud-trace-exporter/src/trace.ts#L42

For example

```ts
const exporter = new TraceExporter({ projectId: "my-project" });
```

**Comment by thanaratjaruenying** [comment]
> > ```
> > *MY_GCP_CREDENTIALS contains project id*
> > const exporter =  new TraceExporter({ credentials: MY_GCP_CREDENTIALS })
> > provider.addSpanProcessor(new BatchSpanProcessor(exporter))
> > ```
> 
> The credentials object shouldn't have project ID. You can pass the project ID directly in the options:
> 
> https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/b80a2b6fd17dc9fce74b2aad4bc19e97dba8f286/packages/opentelemetry-cloud-trace-exporter/src/trace.ts#L42
> 
> For example
> 
> ```ts
> const exporter = new TraceExporter({ projectId: "my-project" });
> ```

yes, there is `{project_id: foo}`, just not in the right case
