### ISSUE TITLE
GKE resources support

### ISSUE THREAD

**Issue by emmekappa** [GoogleCloudPlatform/opentelemetry-operations-js#311]
OpenTelemetry GCP detectors [supports GKE resources](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-resource-detector-gcp/src/detectors/GcpDetector.ts) but unfortunately those seems not to be shipped by Cloud Trace Exporter.

**Comment by aabmass** [comment]
That's correct, the relevant code is here https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/a44657692b456635f131f231bedd5f34f119c21c/packages/opentelemetry-resource-util/src/index.ts#L45 Cloud Trace doesn't actually support resources itself, but we do map to a Cloud Monitoring monitored resource e.g. for k8s [k8s_container](https://cloud.google.com/monitoring/api/resources#tag_k8s_container) and attach that as special labels.

Another option which we implemented in the Python exporter is to give an regex to pass through resource attributes https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/145 which should be pretty straightforward to implement here. Contributions are welcome if you're up for it :)
