### ISSUE TITLE
Cloud Monitoring Exporter creates invalid MetricDescriptor types on Windows

### ISSUE THREAD

**Issue by BlazingAsher** [GoogleCloudPlatform/opentelemetry-operations-js#317]
### What version of OpenTelemetry are you using?
0.24.0

### What version of Node are you using?
16.4

### What did you do?

Use the usage example at https://www.npmjs.com/package/@google-cloud/opentelemetry-cloud-monitoring-exporter on Windows.

### What did you expect to see?

Metrics would be exported and viewable on the Google Cloud Monitoring UI.

### What did you see instead?

No metrics are exported.

When you attach a DiagConsoleLogger to OpenTelemetry, you can see that the request to create a MetricDescriptor fails with the message: `Field metricDescriptor.type had an invalid value of "custom.googleapis.com\\opentelemetry\\metric_name": The metric type must be a URL-formatted string with a domain and non-empty path.`.

Since `path.join()` is used to create the type, all the forward slashes are replaced with back slashes on Windows, rendering the type invalid.

### Additional context
Works as expected on Linux.

**Comment by aabmass** [comment]
Thanks for the awesome bug report and root causing this @BlazingAsher. PRs are always welcome if you have the time 😃 just let me know and I can assign this to you, otherwise I will try to fix this in the coming weeks.

**Comment by BlazingAsher** [comment]
Sure, I can put together a PR in a couple days.
