### ISSUE TITLE
Spans not connecting properly to root or not visible at all in Trace dashboard

### ISSUE THREAD

**Issue by TriPSs** [GoogleCloudPlatform/opentelemetry-operations-js#337]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
```
    "@opentelemetry/api": "^1.0.3",
    "@opentelemetry/instrumentation-dns": "^0.25.0",
    "@opentelemetry/instrumentation-graphql": "^0.25.0",
    "@opentelemetry/instrumentation-http": "^0.25.0",
    "@opentelemetry/instrumentation-mysql": "^0.25.0",
    "@opentelemetry/instrumentation-nestjs-core": "^0.25.0",
    "@opentelemetry/resource-detector-gcp": "^0.25.0",
    "@opentelemetry/sdk-trace-base": "^1.0.0",
    "@opentelemetry/sdk-trace-node": "^1.0.0",
    "@opentelemetry/tracing": "^0.24.0",
```

### What version of Node are you using?
v14.15.1

### What did you do?
I enabled tracing in my API that is running on Cloud Run, with the following instructrions
```
registerInstrumentations({
    instrumentations: [
      new DnsInstrumentation(),
      new MySQLInstrumentation(),
      new NestInstrumentation(),
      new HttpInstrumentation(),
      new GraphQLInstrumentation({
        mergeItems: true
      })
    ]
  })
```

Only the Fastify requests are visible inside the correct root span but all the mysql spans are not connected to the root span, grapql spans are completely missing in google trace.

### What did you expect to see?
To see all the spans connected to the trace like this:
![image](https://user-images.githubusercontent.com/7668692/135665767-54c5e272-470d-44e6-828e-10febfdeeb22.png)

As you can see in the image, if I use Jaegur as exporter everything works as expected.

### What did you see instead?
![image](https://user-images.githubusercontent.com/7668692/135665892-8bfda118-4e82-42ca-aa5c-835373a6c8d7.png)

**Comment by TriPSs** [comment]
After downgrading everything to the same version as `opentelemetry-cloud-trace-exporter` it worked.

**Comment by aabmass** [comment]
FYI `@opentelemetry/tracing` was renamed to `@opentelemetry/sdk-trace-base` so you don't need both anymore.

NPM should be complaining that the peer dependencies of `@google-cloud/opentelemetry-cloud-trace-exporter` are not met if the versions are mismatched. Not sure why you weren't getting that. Regardless, with the OTel 1.0 release just made, this should be a problem of the past once I release the Google packages for the new version
