### ISSUE TITLE
The 'googleapis' library is too large size

### ISSUE THREAD

**Issue by anchan828** [GoogleCloudPlatform/opentelemetry-operations-js#396]
I was using `webpack-bundle-analyzer` to check the included libraries and found that the `googleapis` library contains 16MB.
Since this library is only used by `@google-cloud/opentelemetry-cloud-monitoring-exporter`, could it be replaced by `@google-cloud/monitoring` instead?

![366aaa84926dfa5cee15356ea260430c](https://user-images.githubusercontent.com/694454/163900627-f793981f-e2fa-40b1-880d-806d46d9fab3.jpg)

**Comment by aabmass** [comment]
Thanks for opening an issue about this

> could it be replaced by @google-cloud/monitoring instead

I think this would be a great enhancement but don't have time to work on it right now.
