### ISSUE TITLE
Loading of protos at runtime does not place nice with bundlers

### ISSUE THREAD

**Issue by SoftMemes** [GoogleCloudPlatform/opentelemetry-operations-js#404]
### What version of OpenTelemetry are you using?

1.2.0

### What version of Node are you using?

16

### What did you do?

I'm using the Google trace exporter in a Next.js project as well as with a backend service bundled using esbuild. In both of these cases, the trace exporter fails at runtime when trying to initializer grpc. 

```
Google Cloud Trace authenticating
Google Cloud Trace got authentication. Initializaing rpc client
failed to create client: ENOENT: no such file or directory, open '[mydir]/google/devtools/cloudtrace/v2/tracing.proto'
{"stack":"Error: failed to create client: ENOENT: no such file or directory, open '[mydir]/google/devtools/cloudtrace/v2/tracing.proto'","message":"failed to create client: ENOENT: no such file or directory, open '[mydir]/google/devtools/cloudtrace/v2/tracing.proto'","errno":"-2","code":"ENOENT","syscall":"open","path":"[mydir]/google/devtools/cloudtrace/v2/tracing.proto","name":"Error"}
```

"[mydir]" is part of my project directory structure, but in fact one level above the project root when running from `dist` and a bundled version of my service.

It appears that the shared google proto library assumes that it lives in a flat `node_modules` directory and tries to find the protos in `../..` relative to it - https://github.com/googleapis/nodejs-proto-files/blob/main/src/index.ts#L19, referenced from https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/main/packages/opentelemetry-cloud-trace-exporter/src/trace.ts#L141

A similar error occurs when running under Next.

### What did you expect to see?

Protos being found automatically.

### What did you see instead?

A proto file failed to load due to assumptions about directory structure.

### Additional context

Ideally the protos would be bundled in such a way that esbuild or other tools could include the content, e.g. as a string content instead of a .proto file, but barring that, it would be useful to be able to at least point to the directory containing protos so that these could be copied over and referred to explicitly.

**Comment by kjlis** [comment]
Hi! Any update on this? I'm experiencing the same issue.

**Comment by aabmass** [comment]
Thanks for opening an issue. If anyone would like to give this issue a shot, please leave a comment and I can assign this to you.

**Comment by SoftMemes** [comment]
FWIW, I have ended up manually copying the files into the location that the code expects for production (in a directory relative to my bundled output file), though I consider this a workaround at best and would still love to see this case supported officially.

**Comment by bradleybeighton** [comment]
Hi, is there an update on this? Experiencing with NestJS

**Comment by aabmass** [comment]
As this keeps coming up I took a look into what it would take to fix things. There are sort of two options here

1. Generate a real client library (as a separate package outside of this repo) and use that client library instead of gRPC directly. That should have the best practices wrapped up in it, including retries.
2. Use `pbjs` to generate JSON files as part of our build that can be imported directly instead of loading the `.proto` files. I believe bundlers would understand the JS import and automatically bundle the needed code.

Option 1 requires some work from our side, but option 2 could be implemented by anyone :) Again if anyone would like to take a crack at option 2, please leave a comment and I'll assign the issue to you 🙂

**Comment by MichaelDoyle** [comment]
@aabmass Can you take a look at https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/741 above?
