### ISSUE TITLE
Add support for array attributes

### ISSUE THREAD

**Issue by henrinormak** [GoogleCloudPlatform/opentelemetry-operations-js#440]
*Is your feature request related to a problem? Please describe.*
OpenTelemetry Spans support attributes with array values, these attributes are currently not exported to CloudTrace. This is not notified of in any way (at least not that I can identify), which leads to application developers suspecting faults in their use of the library.

*Describe the solution you'd like*
[Code that transforms Spans](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/main/packages/opentelemetry-cloud-trace-exporter/src/transform.ts#L204-L218) should support array types from the [list of allowed types](https://github.com/open-telemetry/opentelemetry-js-api/blob/main/src/common/Attributes.ts#L31-L37). This might require changes in CloudTrace APIs, which I can also file a feature request for, presumably [here](https://issuetracker.google.com/issues?q=status:open%20componentid:187216&s=created_time:desc)?

*Describe alternatives you've considered*
There are workarounds, like concatenating values into a singular string, but that's hacky, especially as OpenTelemetry Spans do allow for array types of attributes.

**Comment by aabmass** [comment]
Thanks for raising this. The OTel spec actually has [this section](https://github.com/dashpole/opentelemetry-specification/blob/07bfc90007e2eeb89a8104d4474deb6f9f8a1459/specification/common/common.md#:~:text=For%20protocols%20that%20do%20not%20natively%20support%20non%2Dstring%20values%2C%20non%2Dstring%20values%20SHOULD%20be%20represented%20as%20JSON%2Dencoded%20strings.%20For%20example%2C%20the%20expression%20int64(100)%20will%20be%20encoded%20as%20100%2C%20float64(1.5)%20will%20be%20encoded%20as%201.5%2C%20and%20an%20empty%20array%20of%20any%20type%20will%20be%20encoded%20as%20%5B%5D.):

> For protocols that do not natively support non-string values, non-string values SHOULD be represented as JSON-encoded strings.  For example, the expression `int64(100)` will be encoded as `100`, `float64(1.5)` will be encoded as `1.5`, and an empty array of any type will be encoded as `[]`.

You're welcome to open a feature request for array types, but it probably won't be a quick process. Even though it's hacky, I think the JSON approach would be the best here.

**Comment by aabmass** [comment]
@dashpole any thoughts on if we should do this? We also currently attributes of slice type in our Go exporter as well:

https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/36f91511cfd7be17370e23c36ee839a70cdc914d/exporter/trace/trace_proto.go#L314-L338

**Comment by henrinormak** [comment]
I can definitely open a PR for the JSON approach, my only question would be whether that would look decent on CloudTrace UI or not? I assume, filtering etc. won't work properly? Would it still make sense to open a feature request on the CloudTrace product as an entirety and in the meanwhile at least implement the stringification on the exporter level?

**Comment by dashpole** [comment]
> my only question would be whether that would look decent on CloudTrace UI or not? I assume, filtering etc. won't work properly?

If we add array attributes as json strings, it probably wouldn't look great.  Also, if string array attributes are ever supported, switching from json strings to the string array would technically be breaking.  If we supported string arrays as json, we could put it behind a config option so that we could add support in the future (for users that don't enable the option).

**Comment by aabmass** [comment]
@henrinormak would that work for you?

**Comment by henrinormak** [comment]
Sounds reasonable, I'm not too familiar with the package, but I can try and add this configurability to my PR linked above.
