### ISSUE TITLE
Cannot read properties of undefined getMeterProvider

### ISSUE THREAD

**Issue by gajus** [GoogleCloudPlatform/opentelemetry-operations-js#444]
### What happened?

Provided setup code.

Based on the documentation available, I expect this code to work, but instead it is throwing an error.

### OpenTelemetry Setup Code

```JavaScript
// tracing.js

import { TraceExporter } from '@google-cloud/opentelemetry-cloud-trace-exporter';
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';
import { NodeSDK } from '@opentelemetry/sdk-node';

const traceExporter = new TraceExporter();

const sdk = new NodeSDK({
  instrumentations: [getNodeAutoInstrumentations()],
  traceExporter,
});

void sdk.start();
```

### package.json

```JSON
"@google-cloud/opentelemetry-cloud-trace-exporter": "^1.1.0",
"@opentelemetry/auto-instrumentations-node": "^0.34.0",
"@opentelemetry/sdk-node": "^0.34.0",
```

### Relevant log output

```shell
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading 'getMeterProvider')
    at registerInstrumentations (/srv/node_modules/@opentelemetry/sdk-node/node_modules/@opentelemetry/instrumentation/build/src/autoLoader.js:30:66)
    at NodeSDK.start (/srv/node_modules/@opentelemetry/sdk-node/build/src/sdk.js:140:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by gajus** [comment]
Seems like the fix is to simply update dependencies

https://github.com/open-telemetry/opentelemetry-js/issues/3412#issuecomment-1315646712

**Comment by aabmass** [comment]
@gajus sounds like this is resolved then. Please re-open if there is some action needed in this repo.

**Comment by gajus** [comment]
@aabmass It is not. This package needs to update dependencies.

**Comment by gajus** [comment]
@aabmass Can you re-open the issue until dependencies are updated?

**Comment by gajus** [comment]
CC @mayurkale22 @shivkanya9146 @TigerHe7

**Comment by schlenks** [comment]
@aabmass would you re-open this issue since the package has not had it's dependencies updated?

**Comment by aabmass** [comment]
The dependencies were updated in https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/446

Please hang on for a release https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/452

**Comment by ishamishra0408** [comment]
@gajus did it work for you? I am getting the same error, still.
