### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sam-throne** [GoogleCloudPlatform/opentelemetry-operations-js#452]
Hi there,

Could you please create a new npm release including #446 ? I'm currently blocked from integrating this in our project.

Thanks!
Sam

**Comment by aabmass** [comment]
The release is planned for Monday

**Comment by aabmass** [comment]
Released https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/tag/v1.2.0%2Fv0.15.0
