### ISSUE TITLE
Instructions for setting it up with @opentelemetry/auto-instrumentations-node

### ISSUE THREAD

**Issue by gajus** [GoogleCloudPlatform/opentelemetry-operations-js#471]
Can you provide documentation as to how to use this with `@opentelemetry/sdk-node` and `@opentelemetry/auto-instrumentations-node`? The latter two seem to be the recommended way to add open telemetry to Node.js.

**Comment by aabmass** [comment]
Did you see the upstream documentation? You can pass the trace exporter provided in this repo when you call `new opentelemetry.NodeSDK()`. You can follow [this example](https://github.com/open-telemetry/opentelemetry-js#set-up-tracing) with these changes:

```diff
-const { ConsoleSpanExporter } = require('@opentelemetry/sdk-trace-base');
+const { TraceExporter } = require('@google-cloud/opentelemetry-cloud-trace-exporter');
// ...
-const traceExporter = new ConsoleSpanExporter()
+const traceExporter = new TraceExporter();
```

**Comment by aabmass** [comment]
@gajus please re-open if you have more questions.
