### ISSUE TITLE
Cut a new release for histogram fix

### ISSUE THREAD

**Issue by johnrichardrinehart** [GoogleCloudPlatform/opentelemetry-operations-js#509]
We're doing the same as https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/473#issuecomment-1373055658 in light of #473 and #474 . Can a new release be cut so that I can rely on the official package instead of an internally-maintained fork?

**Comment by justin--** [comment]
In the same boat would really appreciate just bumping the versions to be able to use that recent fix.

**Comment by dashpole** [comment]
We will do this next week (Jan 30th - Feb 3rd)

**Comment by aabmass** [comment]
Newest release contains the fix https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/tag/v2.0.0%2Fv0.16.0

**Comment by johnrichardrinehart** [comment]
Ideal. Thank you. I'll close once we update our dep in prod and confirm it's all good. Please wait up to 48h. If I haven't circled back after that time then please feel free to close.
