### ISSUE TITLE
Inconsistent documentation with `sdk-trace-web`

### ISSUE THREAD

**Issue by gbdubs** [GoogleCloudPlatform/opentelemetry-operations-js#551]
**Problem**: 

The [Online Documentation for Cloud Trace](https://cloud.google.com/trace/docs/setup/nodejs-ot) encourages users to [set up client-side tracing using `@opentelemetry/sdk-trace-web`] alongside export via `@google-cloud/opentelemetry-cloud-trace-exporter`. However, after several hours of trying to get this working, I finally figured out what is stated in #114 about the exporter: "This exporter is for node only, it cannot be used for browser export". Since `sdk-trace-web` is generating traces client side, and `@google-cloud/opentelemetry-cloud-trace-exporter` is incompatible with that.

**Proposed Solutions**

1 - implement an endpoint that would function as the workaround in #114 proposes as a core functionality of Cloud Trace. It would be HUGELY valuable for folks like me that would prefer to not implement pass through cloud functions to ingest trace data.
2 - Update the first-linked documentation to remove any mention of `sdk-trace-web` since it is fully incompatible with the ingestion techniques described there, and thus there is no mechanism (that I can see) by which the end-user could arrive at a working solution.

**Comment by damemi** [comment]
Thanks for reporting this, we have a bug to track this internally. Closing this so it's tracked in one place.

**Comment by gajus** [comment]
What's the correct way to ingest client side generated traces into Cloud Trace?

FYI also asked the same question here https://stackoverflow.com/questions/76789714/how-to-ingest-browser-opentelemetry-traces-in-cloud-trace

**Comment by gbdubs** [comment]
As I understand it, the correct way is to forward those logs to a server you are running (or a cloud function, etc) and then export them to Cloud Trace. That's the best answer I've yet heard, and in my (albeit brief) search for code that accomplishes this out of the box, I wasn't able to find any.
