### ISSUE TITLE
"service.name" span attribute not mapped to service name in trace list

### ISSUE THREAD

**Issue by Conduitry** [GoogleCloudPlatform/opentelemetry-operations-js#552]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?

I'm not sure which specific package this is referring to. Here is my `package.json` for my repro below.

```
{
	"dependencies": {
		"@google-cloud/opentelemetry-cloud-trace-exporter": "2.0.0",
		"@opentelemetry/api": "1.4.1",
		"@opentelemetry/sdk-trace-base": "1.13.0",
		"@opentelemetry/sdk-trace-node": "1.13.0"
	},
	"type": "module"
}
```

### What version of Node are you using?

20.1.0

### What did you do?

I sent a span with a `service.name` attribute. 

```
import * as opentelemetry from "@opentelemetry/api"
import { SimpleSpanProcessor } from "@opentelemetry/sdk-trace-base"
import { NodeTracerProvider } from "@opentelemetry/sdk-trace-node"
import { TraceExporter } from "@google-cloud/opentelemetry-cloud-trace-exporter"

const provider = new NodeTracerProvider()

provider.addSpanProcessor(new SimpleSpanProcessor(new TraceExporter()))

provider.register()

const tracer = opentelemetry.trace.getTracer("foo")

tracer.startActiveSpan("test", async (span) => {
	span.setAttribute("service.name", "foo")
	await new Promise((res) => setTimeout(res, 1000))
	span.end()
})
```

### What did you expect to see?

I expected this to display as "Service - foo" in the "Details" portion of the view for a specific span on https://console.cloud.google.com/traces/list.

### What did you see instead?

This displayed as a "service.name" in the "Labels" portion.

### Additional context

The Go trace exporter translates the `service.name` attribute name to `g.co/gae/app/module`, which does not happen in the JS one. If I set the attribute with this Google-specific name instead, I get the behavior I'm looking for. I assume that this is a bug in the JS trace exporter, and that it should also automatically be remapping `service.name` to `g.co/gae/app/module`.

**Comment by solsu01** [comment]
@Conduitry - we are in the process of making the Cloud Trace UI interpret and display OTel conventions in a more user friendly manner.

**Comment by aabmass** [comment]
Following onto what @solsu01 said, we'd rather not implement this here if a UI fix is coming. The workaround feels like a hack since it is tied to GAE which you're probably not using anyway.

**Comment by Conduitry** [comment]
Do you have any sort of timeline on when I should check back to see whether it's working and try to switch to `service.name`?

Do you plan on removing the rewrite in the Go trace exporter for consistency once it's handled in the UI?

**Comment by aabmass** [comment]
> Do you have any sort of timeline on when I should check back to see whether it's working and try to switch to `service.name`?

@solsu01 any comment here?

> Do you plan on removing the rewrite in the Go trace exporter for consistency once it's handled in the UI?

yes most likely we would remove that extra bit of mapping code

**Comment by solsu01** [comment]
You should be able to see service.name displayed as a column in trace details this week.

**Comment by Conduitry** [comment]
It looks like the new trace explorer UI is now live, and it looks awesome! Thank you to everyone who was part of that!

**Comment by geshan** [comment]
was the service name issue solved for GCP?
