### ISSUE TITLE
Support exponential histogram in the exporter

### ISSUE THREAD

**Issue by aabmass** [GoogleCloudPlatform/opentelemetry-operations-js#555]
This was added in the 1.14 and needs to be wired into the exporter.

**Comment by justin--** [comment]
Just found out about this too and would like to be able to use it.

**Comment by justin--** [comment]
Will a new version be published that includes this and other latest changes?

I also see that https://github.com/open-telemetry/opentelemetry-js/issues/3931 was closed and looks to have a fix in. Does that also need a version bump?

Appreciate getting this addressed though, excited to be able to use this!

**Comment by aabmass** [comment]
Upstream will probably do a release soon, but I'm not sure when. I will try to release this repo next week
