### ISSUE TITLE
opentelemetry-cloud-trace-exporter does not stack trace through multiple cloud run services

### ISSUE THREAD

**Issue by sytdas** [GoogleCloudPlatform/opentelemetry-operations-js#585]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
1.4.1

### What version of Node are you using?
18

### What did you do?
I set up a sample repo, service-one receives request then send it to service-two
https://github.com/sytdas/tracejs

### What did you expect to see?
The trace includes service-one and service-two
![image](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/assets/110009581/44dc5146-167d-48ae-a071-f109eee7d584)

### What did you see instead?
Cloud trace shows trace for service-one and service-two separately 
![image](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/assets/110009581/778d543d-8917-4dc2-b9d7-a88abba76e73)

![Screenshot 2023-07-17 at 10 54 41](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/assets/110009581/ea618557-faab-4f09-90d1-1ecd59a3f189)

**Comment by aabmass** [comment]
For the Jaeger screenshot, were the applications running in Cloud Run or locally? This looks like a propagation issue and the exporter shouldn't affect this.

**Comment by sytdas** [comment]
@aabmass  The first picture is applications run on my localhost. 2nd and 3rd pictures of deployed app on cloud run and its trace.

**Comment by sytdas** [comment]
I found that Cloud Trace use different header than opentelemetry. 😞  
```
"x-cloud-trace-context: 49f0d6a0b5ae486cf56c936167a8fdc1/7488432643372146419;o=1"
"traceparent: 00-49f0d6a0b5ae486cf56c936167a8fdc1-67ec41d050a2def3-01"
```
