### ISSUE TITLE
Verify non-GKE resources map to `k8s_*` monitored resources

### ISSUE THREAD

**Issue by damemi** [GoogleCloudPlatform/opentelemetry-operations-js#594]
From https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/627, verify that kubernetes resources do not require `cloud.platform: gcp_kubernetes_engine` to map to k8s Monitored Resources (`k8s_container`, `k8s_pod`, etc).

Go exporter/collector fix in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/683 uses `k8s.cluster.name` resource attribute to identify a k8s resource. Other languages should be consistent with this.

**Comment by tkmsaaaam** [comment]
I created this PR. #724  Please review it.
