### ISSUE TITLE
Monitoring: Cannot have label with value of integer

### ISSUE THREAD

**Issue by davidwitten** [GoogleCloudPlatform/opentelemetry-operations-js#77]
### What version of OpenTelemetry are you using?
@opentelemetry/metrics: 0.7.0
@google-cloud/opentelemetry-cloud-monitoring-exporter: 0.3.0

### What version of Node are you using?
v10.20.1

### What did you do?
I copied the example in this repo, changing the final line to match the example in the OpenTelemetry Prometheus Exporter: https://github.com/open-telemetry/opentelemetry-js/blob/master/examples/prometheus/index.js (`labels = {pid: process.pid}`)

```
const { MeterProvider }  = require('@opentelemetry/metrics');
const { MetricExporter } = require('@google-cloud/opentelemetry-cloud-monitoring-exporter');

const exporter = new MetricExporter();

// Register the exporter
const meter = new MeterProvider({
  exporter,
  interval: 60000,
}).getMeter('example-meter');

// Now, start recording data
const counter = meter.createCounter('metric_name');
counter.add(10, {pid, process.pid}); // Changed this line 
```

### What did you expect to see?
I expected to see valid metrics in Google Cloud. This exact code works with the Prometheus Exporter, so I expected it to work with the Google Cloud exporter as well. 

### What did you see instead?
```
(node:3896) UnhandledPromiseRejectionWarning: Error: Invalid value at 'time_series[0].metric.labels[0].value' (TYPE_STRING), 3896
    at Gaxios._request (/home/davidwitten_google_com/project-2/food_finder/node_modules/gaxios/build/src/gaxios.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Additional context
I was able to get around this issue in two separate ways:

1) I converted the number to a string:
```
counter.add(10, {pid, `${process.pid}`});
```

2) Within [transform.ts](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/master/packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts#L132), I converted the value to a string.

```
labels[keys[i]] = `${metric.labels[keys[i]]}`;
```

I'll submit a PR with that change to transform.ts, along with additional tests.

**Comment by mayurkale22** [comment]
> Within transform.ts , I converted the value to a string.

This solution makes sense to me. As per https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries#Metric the label values needs to be in the form of string only.

Feel free to open PR to address this. Thank you :)
