### ISSUE TITLE
Monitoring: Metrics don't appear under any resource type

### ISSUE THREAD

**Issue by davidwitten** [GoogleCloudPlatform/opentelemetry-operations-js#79]
*Is your feature request related to a problem? Please describe.*

I was exporting my metrics to Google Cloud. When I previously used OpenCensus and the Stackdriver Exporter, I was able to see my metrics when I selected a resource type.
![Screenshot 2020-05-29 at 6 02 42 PM](https://user-images.githubusercontent.com/3642085/83309205-a619bf80-a1d6-11ea-8d4a-3f95d69730ab.png) 

However, now I can only see data when I specify the "Global" resource type. 
![Screenshot 2020-05-29 at 5 26 46 PM - Display 2](https://user-images.githubusercontent.com/3642085/83309251-c9dd0580-a1d6-11ea-9364-ab2c98ec62bc.png)

*Describe the solution you'd like*
Within the Stackdriver exporter [code](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-exporter-stackdriver/src/common-utils.ts), they specify the resource type.  

Currently, this repository sets the resource to "Global" with a comment in the code [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/master/packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts#L112) to wait until the OT API exists.

It seems that the OpenTelemetry resource API [exists now](https://github.com/open-telemetry/opentelemetry-js/tree/master/packages/opentelemetry-resources), so I'll try to add this feature and make a PR with this change.

**Comment by mayurkale22** [comment]
Exporters can get access to `Resource` field via `MetricRecord`. This has been added in SDK in https://github.com/open-telemetry/opentelemetry-js/pull/1049. This feature is released in [v0.8.1](https://github.com/open-telemetry/opentelemetry-js/releases/tag/v0.8.1). I think it is good time to incorpoorate `Resource` into Monitoring exporter.

**Comment by mayurkale22** [comment]
I can assign this issue to you, if you're working on it.

**Comment by davidwitten** [comment]
Yeah, I'd be happy to work on this issue.

**Comment by davidwitten** [comment]
Hi, just to make sure I'm doing it in a preferred way, within [createTimeSeries](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/master/packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts#L113), I'm calling [detectResources](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-resources/src/platform/node/detect-resources.ts#L27), which will determine if it is an AWS EC2 instance or a GCP VM instance. Then, I convert it to the correct format for Google Cloud. 

There is an option for the user to enter the resource [themselves](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-metrics/src/MeterProvider.ts#L34), so should I incorporate that somehow?

**Comment by james-bebbington** [comment]
I'd wait for @mayurkale22 to respond as well, but I believe you should primarily just be using the resource that the user has supplied themselves (in the MeterProvider constructor).

While we do also want to provide the option for the resource to be auto-detected, I'm hoping / expecting this will be included as a core SDK feature rather than needing to be implemented in each exporter, see: https://github.com/open-telemetry/oteps/pull/111

**Comment by mayurkale22** [comment]
I absolutely agree with @james-bebbington. The responsibility of the exporter is only to receive the `Resource` (auto-detected by SDK) and covert it into the appropriate format. Currently, the only SDK resource is attached to the `MeterProvider`[1] and `TracerProvider`[2].

[1] https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-metrics/src/Meter.ts#L52
[2] https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-tracing/src/BasicTracerProvider.ts#L40

I would suggest to open issue in https://github.com/open-telemetry/opentelemetry-js repo to attach auto-detected resource in SDK.

**Comment by davidwitten** [comment]
Thanks @james-bebbington and @mayurkale22! I just added the resource from the MetricProvider instead of automatically detecting it

**Comment by dashpole** [comment]
[Triage] I believe this was accomplished by #85 above.  Much has also changed since this issue was opened.  Feel free to open a new issue if this is still a problem.
