### ISSUE TITLE
cloud storage instrumentation

### ISSUE THREAD

**Issue by naseemkullah** [GoogleCloudPlatform/opentelemetry-operations-js#81]
*Is your feature request related to a problem? Please describe.*
Would like a package to auto instrument https://www.npmjs.com/package/@google-cloud/storage

*Describe the solution you'd like*
`opentelemetry-instrumentation-gcs`

*Describe alternatives you've considered*
Manually add spans.

**Comment by naseemkullah** [comment]
Not sure, but maybe it would make sense to instrument this common lib first/instead: https://www.npmjs.com/package/@google-cloud/common

**Comment by naseemkullah** [comment]
It has come to my attention that http instrumentation should encompass all calls to GCS. Closing.

**Comment by kintel** [comment]
Would it be possible to post the source code of a minimal example app to help diagnosing this?

**Comment by naseemkullah** [comment]
I may need to have the `https` plugin enabled. will update soon.

**Comment by naseemkullah** [comment]
@kintel My mistake, with `https` plugin enabled I can clearly see calls to GCS. Closing!
