### ISSUE TITLE
Linter: ESLint couldn't find a configuration file

### ISSUE THREAD

**Issue by davidwitten** [GoogleCloudPlatform/opentelemetry-operations-js#84]
### What did you do?
I made changes to code and planned on running the linter before submitting a PR.

So, I ran `npm run lint`

### What did you expect to see?

This is an example when running in the opentelemetry-exporter-collector package:
```
> @opentelemetry/exporter-collector@0.7.0 lint /home/davidwitten_google_com/opentelemetry-js/packages/opentelemetry-exporter-collector
> gts check
```

### What did you see instead?
```
> @google-cloud/opentelemetry-cloud-monitoring-exporter@0.3.0 lint /home/davidwitten_google_com/opentelemetry-operations-js/packages/opentelemetry-cloud-monitoring-exporter
> gts check
version: 10
Oops! Something went wrong! :(
ESLint: 7.1.0
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:
    eslint --init
ESLint looked for configuration files in /home/davidwitten_google_com/opentelemetry-operations-js/packages/opentelemetry-cloud-monitoring-exporter/build/src and its ancestors. If it found none, it then looked in your home directory.
If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://eslint.org/chat
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @google-cloud/opentelemetry-cloud-monitoring-exporter@0.3.0 lint: `gts check`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @google-cloud/opentelemetry-cloud-monitoring-exporter@0.3.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/davidwitten_google_com/.npm/_logs/2020-06-02T21_00_59_109Z-debug.log
```

### Additional context
I noticed in other repositories (e.g. [Prometheus exporter](https://github.com/open-telemetry/opentelemetry-js/tree/master/packages/opentelemetry-exporter-prometheus), [OpenTelemetry core](https://github.com/open-telemetry/opentelemetry-js/tree/master/packages/opentelemetry-core), etc.), they include a [.eslintrc.js](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-core/.eslintrc.js) file and a [eslint.config.js](https://github.com/open-telemetry/opentelemetry-js/blob/master/eslint.config.js) file in the root directory.

Could I add these files to this repository?

**Comment by TigerHe7** [comment]
I'm currently looking into this issue.

Noticing that `lerna run lint` doesn't work immediately after adding those config files, so I'm looking at what other tweaks might be necessary.

**Comment by jonahrosenblum** [comment]
I made the same changes as @davidwitten and ran into the issue of having a few extra errors that do not appear when the CI linting runs. These issues would be very easy to fix and would not change any code. 8 of the errors are about making the headers block comments and the last one would require adding a package to the package.json file. I was wondering if people would want me to fix these and commit the new files in a pull request to address this?

**Comment by aabmass** [comment]
@jonahrosenblum if linting is not currently working and running in CI, it would be great if you could get it working :smiley:

**Comment by punya** [comment]
Fixed.
