### ISSUE TITLE
Use gRPC to write spans to cloudtrace

### ISSUE THREAD

**Issue by reggiemcdonald** [GoogleCloudPlatform/opentelemetry-operations-js#94]
*Is your feature request related to a problem? Please describe.*
As noted by @mayurkale22

The current implementation of the js trace exporter sends data to cloudtrace using HTTP:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/5c6d7733e54f69aa1412ef9d0a9f8a2b99f6a4c1/packages/opentelemetry-cloud-trace-exporter/src/trace.ts#L98-L121

This is inconsistent with the other exporter implementations which use gRPC: 
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/ec6b73c1970b009e48adce4d59d6dbbc97ba736e/exporter/trace/trace.go#L67

*Describe the solution you'd like*
Re-implement this to send data to cloudtrace using gRPC.

*Additional context*
Relevant usage of gRPC in the exporter collector: 
https://github.com/open-telemetry/opentelemetry-js/blob/837322ff05a7a8118a78f83b4f58be799ee5ce80/packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporter.ts#L100

**Comment by reggiemcdonald** [comment]
@mayurkale22  can you assign @reggiemcdonald  and @TigerHe7 to this

**Comment by mayurkale22** [comment]
@TigerHe7 pls comment on this issue, inorder to assign to you.

**Comment by TigerHe7** [comment]
Thanks!
